allowBuilds:
  '@fortawesome/fontawesome-free': true
  esbuild: true

patchedDependencies:
  mac-scrollbar@0.13.8: patches/mac-scrollbar@0.13.8.patch
  vite-plugin-monaco-editor@1.1.0: patches/vite-plugin-monaco-editor@1.1.0.patch
