// Generated by Tools/Art/Mobile/rebuild_mascot.py. Do not hand-edit.
export const MASCOT_CELL_SIZE = 272;
export const MASCOT_PIVOT_Y = 248;
export const MASCOT_FRAME_PIVOT_X: number[] = [136.25, 135.5, 136.0, 135.5, 136.0, 136.0, 136.0, 135.5, 135.5, 136.5, 136.0, 136.0, 135.5, 136.0, 135.5, 135.5, 135.5, 136.5, 136.5, 135.5, 136.0, 136.0, 136.0, 135.5];
