# Portable LOVE 11.5 support sources mirrored from Source/3rdParty/Love/xmake.lua.
# Platform backends, the native LOVE main loop, and optional decoder libraries
# stay outside this list. Dora's LoveRuntime supplies the platform adapters.
include_guard(GLOBAL)

set(DORA_LOVE_SOURCE_ROOT "${DORA_SOURCE_ROOT}/3rdParty/Love/src")
file(GLOB DORA_LOVE_BOX2D_SOURCES CONFIGURE_DEPENDS
	"${DORA_LOVE_SOURCE_ROOT}/modules/physics/box2d/*.cpp")
file(GLOB_RECURSE DORA_LOVE_BOX2D_LIBRARY_SOURCES CONFIGURE_DEPENDS
	"${DORA_LOVE_SOURCE_ROOT}/libraries/Box2D/*.cpp")

set(DORA_LOVE_SUPPORT_SOURCES
	${DORA_LOVE_SOURCE_ROOT}/common/Object.cpp
	${DORA_LOVE_SOURCE_ROOT}/common/types.cpp
	${DORA_LOVE_SOURCE_ROOT}/common/Reference.cpp
	${DORA_LOVE_SOURCE_ROOT}/common/Module.cpp
	${DORA_LOVE_SOURCE_ROOT}/common/Exception.cpp
	${DORA_LOVE_SOURCE_ROOT}/common/deprecation.cpp
	${DORA_LOVE_SOURCE_ROOT}/common/runtime.cpp
	${DORA_LOVE_SOURCE_ROOT}/common/Matrix.cpp
	${DORA_LOVE_SOURCE_ROOT}/common/Data.cpp
	${DORA_LOVE_SOURCE_ROOT}/common/Variant.cpp
	${DORA_LOVE_SOURCE_ROOT}/common/StringMap.cpp
	${DORA_LOVE_SOURCE_ROOT}/common/b64.cpp
	${DORA_LOVE_SOURCE_ROOT}/common/pixelformat.cpp
	${DORA_LOVE_SOURCE_ROOT}/libraries/lz4/lz4.c
	${DORA_LOVE_SOURCE_ROOT}/libraries/lz4/lz4hc.c
	${DORA_LOVE_SOURCE_ROOT}/libraries/noise1234/noise1234.cpp
	${DORA_LOVE_SOURCE_ROOT}/libraries/noise1234/simplexnoise1234.cpp
	${DORA_LOVE_BOX2D_LIBRARY_SOURCES}
	${DORA_LOVE_SOURCE_ROOT}/modules/math/BezierCurve.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/math/wrap_BezierCurve.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/math/MathModule.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/math/wrap_Math.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/math/RandomGenerator.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/math/wrap_RandomGenerator.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/math/Transform.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/math/wrap_Transform.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/data/ByteData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/data/CompressedData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/data/Compressor.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/data/DataModule.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/data/DataView.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/data/HashFunction.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/data/wrap_ByteData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/data/wrap_CompressedData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/data/wrap_Data.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/data/wrap_DataModule.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/data/wrap_DataView.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/audio/Filter.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/audio/Source.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/audio/wrap_Source.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/event/Event.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/event/wrap_Event.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/window/Window.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/window/wrap_Window.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/keyboard/Keyboard.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/keyboard/wrap_Keyboard.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/mouse/Cursor.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/mouse/wrap_Cursor.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/mouse/wrap_Mouse.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/touch/wrap_Touch.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/joystick/Joystick.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/joystick/wrap_Joystick.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/joystick/wrap_JoystickModule.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/physics/Body.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/physics/Shape.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/physics/Joint.cpp
	${DORA_LOVE_BOX2D_SOURCES}
	${DORA_LOVE_SOURCE_ROOT}/modules/filesystem/File.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/filesystem/FileData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/filesystem/Filesystem.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/filesystem/wrap_File.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/filesystem/wrap_FileData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/filesystem/wrap_Filesystem.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/font/GlyphData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/font/Rasterizer.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/font/TrueTypeRasterizer.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/font/wrap_Font.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/font/wrap_GlyphData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/font/wrap_Rasterizer.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/Drawable.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/vertex.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/Font.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/Shader.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/Text.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/Video.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/Mesh.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/SpriteBatch.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/ParticleSystem.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/depthstencil.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/Texture.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/Canvas.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_Canvas.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsCanvasConstructor.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/Image.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/Quad.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_Texture.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsDraw.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsDisplayState.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsCapabilities.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsInfo.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsImageConstructor.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsScreenshot.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsFontState.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsFontConstructor.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsPrimitives.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsPrint.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsQuad.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsShaderConstructor.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsState.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_GraphicsShaderState.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_Image.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_Font.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_Shader.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_Text.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_Video.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_Mesh.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_SpriteBatch.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_ParticleSystem.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/graphics/wrap_Quad.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/image/ImageDataBase.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/image/CompressedSlice.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/image/CompressedImageData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/image/FormatHandler.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/image/Image.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/image/ImageData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/image/wrap_Image.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/image/wrap_ImageData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/image/wrap_CompressedImageData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/sound/Decoder.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/sound/Sound.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/sound/SoundData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/sound/wrap_Decoder.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/sound/wrap_Sound.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/sound/wrap_SoundData.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/system/System.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/system/wrap_System.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/timer/wrap_Timer.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/thread/Channel.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/thread/LuaThread.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/thread/wrap_Channel.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/thread/wrap_LuaThread.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/thread/wrap_ThreadModule.cpp
	${DORA_LOVE_SOURCE_ROOT}/modules/video/wrap_VideoStream.cpp
)
