# Portable Dora engine sources shared by native and Web CMake targets.
# Platform targets may filter this list, but must not parse another target file.
include_guard(GLOBAL)

set(DORA_ENGINE_SOURCES
	${DORA_SOURCE_ROOT}/Platformer/AINode.cpp
	${DORA_SOURCE_ROOT}/Platformer/Define.cpp
	${DORA_SOURCE_ROOT}/Platformer/AI.cpp
	${DORA_SOURCE_ROOT}/Platformer/Data.cpp
	${DORA_SOURCE_ROOT}/Platformer/VisualCache.cpp
	${DORA_SOURCE_ROOT}/Platformer/PlatformCamera.cpp
	${DORA_SOURCE_ROOT}/Platformer/Unit.cpp
	${DORA_SOURCE_ROOT}/Platformer/Face.cpp
	${DORA_SOURCE_ROOT}/Platformer/PlatformWorld.cpp
	${DORA_SOURCE_ROOT}/Platformer/BulletDef.cpp
	${DORA_SOURCE_ROOT}/Platformer/Bullet.cpp
	${DORA_SOURCE_ROOT}/Platformer/UnitAction.cpp
	${DORA_SOURCE_ROOT}/Cache/AtlasCache.cpp
	${DORA_SOURCE_ROOT}/Cache/Cache.cpp
	${DORA_SOURCE_ROOT}/Cache/ClipCache.cpp
	${DORA_SOURCE_ROOT}/Cache/ShaderCache.cpp
	${DORA_SOURCE_ROOT}/Cache/ParticleCache.cpp
	${DORA_SOURCE_ROOT}/Cache/TextureCache.cpp
	${DORA_SOURCE_ROOT}/Cache/SkeletonCache.cpp
	${DORA_SOURCE_ROOT}/Cache/ModelCache.cpp
	${DORA_SOURCE_ROOT}/Cache/Model3DCache.cpp
	${DORA_SOURCE_ROOT}/Cache/DragonBoneCache.cpp
	${DORA_SOURCE_ROOT}/Cache/AudioCache.cpp
	${DORA_SOURCE_ROOT}/Cache/FontCache.cpp
	${DORA_SOURCE_ROOT}/Cache/FrameCache.cpp
	${DORA_SOURCE_ROOT}/Cache/SVGCache.cpp
	${DORA_SOURCE_ROOT}/Cache/TMXCache.cpp
	${DORA_SOURCE_ROOT}/Input/Controller.cpp
	${DORA_SOURCE_ROOT}/Input/Keyboard.cpp
	${DORA_SOURCE_ROOT}/Input/Mouse.cpp
	${DORA_SOURCE_ROOT}/Input/TouchDispather.cpp
	${DORA_SOURCE_ROOT}/Entity/Entity.cpp
	${DORA_SOURCE_ROOT}/Basic/Director.cpp
	${DORA_SOURCE_ROOT}/Basic/AutoreleasePool.cpp
	${DORA_SOURCE_ROOT}/Basic/Object.cpp
	${DORA_SOURCE_ROOT}/Basic/Scheduler.cpp
	${DORA_SOURCE_ROOT}/Basic/Database.cpp
	${DORA_SOURCE_ROOT}/Basic/Content.cpp
	${DORA_SOURCE_ROOT}/Basic/Application.cpp
	${DORA_SOURCE_ROOT}/Effect/Effect.cpp
	${DORA_SOURCE_ROOT}/Effect/Material.cpp
	${DORA_SOURCE_ROOT}/Animation/ModelDef.cpp
	${DORA_SOURCE_ROOT}/Animation/Animation.cpp
	${DORA_SOURCE_ROOT}/Animation/Action.cpp
	${DORA_SOURCE_ROOT}/Lua/LuaFromXml.cpp
	${DORA_SOURCE_ROOT}/Lua/LuaBinding.cpp
	${DORA_SOURCE_ROOT}/Lua/LuaManual.cpp
	${DORA_SOURCE_ROOT}/Lua/LuaCode.cpp
	${DORA_SOURCE_ROOT}/Lua/LuaHandler.cpp
	${DORA_SOURCE_ROOT}/Lua/TealCompiler.cpp
	${DORA_SOURCE_ROOT}/Lua/LuaEngine.cpp
	${DORA_SOURCE_ROOT}/Love/LoveRuntime.cpp
	${DORA_SOURCE_ROOT}/Love/LoveVideoSources.cpp
	${DORA_SOURCE_ROOT}/Love/LoveNode.cpp
	${DORA_SOURCE_ROOT}/Http/HttpServer.cpp
	${DORA_SOURCE_ROOT}/Http/XrtNetwork.c
	${DORA_SOURCE_ROOT}/Wasm/WasmRuntime.cpp
	${DORA_SOURCE_ROOT}/Const/Header.cpp
	${DORA_SOURCE_ROOT}/Common/Utils.cpp
	${DORA_SOURCE_ROOT}/Common/Singleton.cpp
	${DORA_SOURCE_ROOT}/Common/Async.cpp
	${DORA_SOURCE_ROOT}/Common/Debug.cpp
	${DORA_SOURCE_ROOT}/Common/MemoryPool.cpp
	${DORA_SOURCE_ROOT}/Audio/Audio.cpp
	${DORA_SOURCE_ROOT}/3rdParty/ogg/OggSources.c
	${DORA_SOURCE_ROOT}/Audio/VorbisSources.c
	${DORA_SOURCE_ROOT}/Support/Common.cpp
	${DORA_SOURCE_ROOT}/Support/Geometry.cpp
	${DORA_SOURCE_ROOT}/Support/Array.cpp
	${DORA_SOURCE_ROOT}/Support/Value.cpp
	${DORA_SOURCE_ROOT}/Support/Dictionary.cpp
	${DORA_SOURCE_ROOT}/ML/ML.cpp
	${DORA_SOURCE_ROOT}/GUI/ImGuiDora.cpp
	${DORA_SOURCE_ROOT}/GUI/ImGuiBinding.cpp
	${DORA_SOURCE_ROOT}/Render/Camera.cpp
	${DORA_SOURCE_ROOT}/Render/Camera3D.cpp
	${DORA_SOURCE_ROOT}/Render/RenderTarget.cpp
	${DORA_SOURCE_ROOT}/Render/Renderer.cpp
	${DORA_SOURCE_ROOT}/Render/VGRender.cpp
	${DORA_SOURCE_ROOT}/Render/View.cpp
	${DORA_SOURCE_ROOT}/Shader/Builtin.cpp
	${DORA_SOURCE_ROOT}/Shader/ShaderCompiler.cpp
	${DORA_SOURCE_ROOT}/Physics/Joint.cpp
	${DORA_SOURCE_ROOT}/Physics/BodyDef.cpp
	${DORA_SOURCE_ROOT}/Physics/JointDef.cpp
	${DORA_SOURCE_ROOT}/Physics/Body.cpp
	${DORA_SOURCE_ROOT}/Physics/Sensor.cpp
	${DORA_SOURCE_ROOT}/Physics/PhysicsWorld.cpp
	${DORA_SOURCE_ROOT}/Physics/JoltBridge.cpp
	${DORA_SOURCE_ROOT}/Physics/JoltSources.cpp
	${DORA_SOURCE_ROOT}/Physics/DebugDraw.cpp
	${DORA_SOURCE_ROOT}/Node/Particle.cpp
	${DORA_SOURCE_ROOT}/Node/VGNode.cpp
	${DORA_SOURCE_ROOT}/Node/Spine.cpp
	${DORA_SOURCE_ROOT}/Node/Menu.cpp
	${DORA_SOURCE_ROOT}/Node/Sprite.cpp
	${DORA_SOURCE_ROOT}/Node/Grid.cpp
	${DORA_SOURCE_ROOT}/Node/Node.cpp
	${DORA_SOURCE_ROOT}/Node/Node3D.cpp
	${DORA_SOURCE_ROOT}/Node/Surface3D.cpp
	${DORA_SOURCE_ROOT}/Node/Light3D.cpp
	${DORA_SOURCE_ROOT}/Node/Label.cpp
	${DORA_SOURCE_ROOT}/Node/ClipNode.cpp
	${DORA_SOURCE_ROOT}/Node/Model.cpp
	${DORA_SOURCE_ROOT}/Node/Model3D.cpp
	${DORA_SOURCE_ROOT}/Node/Playable.cpp
	${DORA_SOURCE_ROOT}/Node/DragonBone.cpp
	${DORA_SOURCE_ROOT}/Node/DrawNode.cpp
	${DORA_SOURCE_ROOT}/Node/AlignNode.cpp
	${DORA_SOURCE_ROOT}/Node/EffekNode.cpp
	${DORA_SOURCE_ROOT}/Node/TileNode.cpp
	${DORA_SOURCE_ROOT}/Node/AudioSource.cpp
	${DORA_SOURCE_ROOT}/Node/Visual3D.cpp
	${DORA_SOURCE_ROOT}/Node/View3D.cpp
	${DORA_SOURCE_ROOT}/Node/VideoNode.cpp
	${DORA_SOURCE_ROOT}/Node/TIC80Node.cpp
	${DORA_SOURCE_ROOT}/Event/EventType.cpp
	${DORA_SOURCE_ROOT}/Event/EventQueue.cpp
	${DORA_SOURCE_ROOT}/Event/Listener.cpp
	${DORA_SOURCE_ROOT}/Event/Event.cpp
	${DORA_SOURCE_ROOT}/Lua/ToLua/tolua_event.cpp
	${DORA_SOURCE_ROOT}/Lua/ToLua/tolua_map.cpp
	${DORA_SOURCE_ROOT}/Lua/ToLua/tolua_push.cpp
	${DORA_SOURCE_ROOT}/Lua/ToLua/tolua_fix.cpp
	${DORA_SOURCE_ROOT}/Lua/ToLua/tolua_to.cpp
	${DORA_SOURCE_ROOT}/Lua/ToLua/tolua_is.cpp
	${DORA_SOURCE_ROOT}/Lua/Xml/DoraTag.cpp
	${DORA_SOURCE_ROOT}/Lua/Xml/XmlResolver.cpp
	${DORA_SOURCE_ROOT}/Test/Test.cpp
	${DORA_SOURCE_ROOT}/Test/HelloWorldCpp.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yuescript/yue_compiler.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yuescript/ast.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yuescript/yue_ast.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yuescript/yue_parser.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yuescript/yuescript.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yuescript/parser.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yarnflow/yarn_compiler.cpp
	${DORA_SOURCE_ROOT}/3rdParty/implot/implot.cpp
	${DORA_SOURCE_ROOT}/3rdParty/implot/implot_items.cpp
	${DORA_SOURCE_ROOT}/3rdParty/implot/implot_demo.cpp
	${DORA_SOURCE_ROOT}/3rdParty/silly/Slice.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Animation.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/AnimationState.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/AnimationStateData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Atlas.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/AtlasAttachmentLoader.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Attachment.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/AttachmentLoader.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/AttachmentTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Bone.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/BoneData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/BoneLocal.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/BonePose.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/BoneTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/BoundingBoxAttachment.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/ClippingAttachment.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/ColorTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Constraint.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/ConstraintData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/ConstraintTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/ConstraintTimeline1.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/CurveTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/DeformTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/DrawOrder.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/DrawOrderFolderTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/DrawOrderTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Event.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/EventData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/EventTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Extension.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/IkConstraint.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/IkConstraintData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/IkConstraintPose.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/IkConstraintTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/InheritTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Interpolation.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Json.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/LinkedMesh.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/MathUtil.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/MeshAttachment.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/PathAttachment.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/PathConstraint.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/PathConstraintData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/PathConstraintMixTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/PathConstraintPose.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/PathConstraintPositionTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/PathConstraintSpacingTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/PhysicsConstraint.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/PhysicsConstraintData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/PhysicsConstraintPose.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/PhysicsConstraintTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/PointAttachment.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/RTTI.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/RegionAttachment.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/RotateTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/ScaleTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Sequence.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SequenceTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/ShearTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Skeleton.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SkeletonBinary.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SkeletonBounds.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SkeletonClipping.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SkeletonData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SkeletonJson.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SkeletonRenderer.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Skin.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Slider.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SliderData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SliderMixTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SliderPose.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SliderTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Slot.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SlotCurveTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SlotData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SlotPose.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SlotTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/SpineObject.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/TextureLoader.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/TextureRegion.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Timeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/TransformConstraint.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/TransformConstraintData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/TransformConstraintPose.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/TransformConstraintTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/TranslateTimeline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Triangulator.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/Update.cpp
	${DORA_SOURCE_ROOT}/3rdParty/spine/VertexAttachment.cpp
	${DORA_SOURCE_ROOT}/3rdParty/fmt/os.cpp
	${DORA_SOURCE_ROOT}/3rdParty/fmt/format.cpp
	${DORA_SOURCE_ROOT}/3rdParty/imgui/imgui_widgets.cpp
	${DORA_SOURCE_ROOT}/3rdParty/imgui/imgui.cpp
	${DORA_SOURCE_ROOT}/3rdParty/imgui/imgui_tables.cpp
	${DORA_SOURCE_ROOT}/3rdParty/imgui/imgui_demo.cpp
	${DORA_SOURCE_ROOT}/3rdParty/imgui/imgui_draw.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Other/atlas.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Other/utf8.cpp
	${DORA_SOURCE_ROOT}/3rdParty/sqlite/sqlite3.c
	${DORA_SOURCE_ROOT}/3rdParty/stb/stb.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lauxlib.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/liolib.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lopcodes.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lstate.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lobject.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lmathlib.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/loadlib.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lvm.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lfunc.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lstrlib.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/linit.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lstring.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lundump.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lctype.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/ltable.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/ldump.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/loslib.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lgc.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lzio.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/ldblib.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lutf8lib.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lmem.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lcorolib.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lcode.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/ltablib.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lapi.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lbaselib.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/ldebug.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/lparser.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/llex.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/ltm.c
	${DORA_SOURCE_ROOT}/3rdParty/Lua/ldo.c
	${DORA_SOURCE_ROOT}/3rdParty/colib/ljson.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_compile.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_api_libc.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_env.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_exec.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_bind.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_info.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_parse.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_module.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_api_tracer.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_core.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_api_wasi.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_code.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_function.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_api_meta_wasi.c
	${DORA_SOURCE_ROOT}/3rdParty/wasm3/m3_api_uvwasi.c
	${DORA_SOURCE_ROOT}/3rdParty/ml/DecisionTree.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tinyxml2/tinyxml2.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tinyxml2/SAXParser.cpp
	${DORA_SOURCE_ROOT}/3rdParty/lodepng/lodepng.cpp
	${DORA_SOURCE_ROOT}/3rdParty/font/font_manager.cpp
	${DORA_SOURCE_ROOT}/3rdParty/nanovg/nanovg.cpp
	${DORA_SOURCE_ROOT}/3rdParty/nanovg/nanovg_bgfx.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/core/BaseObject.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/core/DragonBones.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/armature/Bone.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/armature/DeformVertices.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/armature/Constraint.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/armature/Armature.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/armature/Slot.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/armature/TransformObject.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/animation/WorldClock.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/animation/TimelineState.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/animation/BaseTimelineState.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/animation/Animation.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/animation/AnimationState.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/parser/BinaryDataParser.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/parser/JSONDataParser.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/parser/DataParser.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/geom/Transform.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/geom/Point.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/model/DragonBonesData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/model/BoundingBoxData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/model/DisplayData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/model/ConstraintData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/model/AnimationConfig.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/model/SkinData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/model/AnimationData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/model/CanvasData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/model/ArmatureData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/model/UserData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/model/TextureAtlasData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/event/EventObject.cpp
	${DORA_SOURCE_ROOT}/3rdParty/dragonBones/factory/BaseFactory.cpp
	${DORA_SOURCE_ROOT}/3rdParty/sqlite/SQLiteCpp/Column.cpp
	${DORA_SOURCE_ROOT}/3rdParty/sqlite/SQLiteCpp/Savepoint.cpp
	${DORA_SOURCE_ROOT}/3rdParty/sqlite/SQLiteCpp/Exception.cpp
	${DORA_SOURCE_ROOT}/3rdParty/sqlite/SQLiteCpp/Statement.cpp
	${DORA_SOURCE_ROOT}/3rdParty/sqlite/SQLiteCpp/Database.cpp
	${DORA_SOURCE_ROOT}/3rdParty/sqlite/SQLiteCpp/Backup.cpp
	${DORA_SOURCE_ROOT}/3rdParty/sqlite/SQLiteCpp/Transaction.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Zip/miniz.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/ZipUtils.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_core_filterops.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_fft_lut.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_core_voicegroup.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_bus.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_fader.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_file.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_audiosource.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_fft.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_core_setters.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_core_voiceops.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_filter.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_queue.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_core_faderops.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_core_basicops.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_thread.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_core_getters.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_core_3d.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/core/soloud_misc.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/filter/soloud_eqfilter.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/filter/soloud_bassboostfilter.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/filter/soloud_echofilter.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/filter/soloud_fftfilter.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/filter/soloud_robotizefilter.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/filter/soloud_dcremovalfilter.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/filter/soloud_lofifilter.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/filter/soloud_flangerfilter.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/filter/soloud_freeverbfilter.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/filter/soloud_biquadresonantfilter.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/filter/soloud_waveshaperfilter.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/backend/sdl/soloud_sdl2.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/backend/sdl/soloud_sdl2_dll.c
	${DORA_SOURCE_ROOT}/3rdParty/soloud/audiosource/wav/stb_vorbis.c
	${DORA_SOURCE_ROOT}/3rdParty/soloud/audiosource/wav/soloud_wavstream.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/audiosource/wav/dr_impl.cpp
	${DORA_SOURCE_ROOT}/3rdParty/soloud/audiosource/wav/soloud_wav.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/StepStats.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/MovementConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/BlockAllocator.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/Version.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/LimitState.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/Math.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/ConstraintSolverConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/DynamicMemory.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/Island.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/Contact.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/ToiOutput.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/StepConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/StackAllocator.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/ToiConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/pmr/PoolMemoryResource.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/pmr/StatsResource.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/pmr/MemoryResource.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/RayCastOutput.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/EdgeShapeConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/Manifold.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/MotorJointConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/Simplex.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/Joint.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/MultiShapeConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/WorldJoint.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/FrictionJointConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/TargetJointConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/SeparationScenario.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/JointConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/Sweep.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/Math.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/UnitVec.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/BodyConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/DiskShapeConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/AABB.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/ContactImpulsesList.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/DynamicTree.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/DistanceProxy.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/RopeJointConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/WorldContact.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/WorldBody.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/TimeOfImpact.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/GearJointConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/AabbTreeWorld.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/Body.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/WheelJointConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/WeldJointConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/WorldShape.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/ContactSolver.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/Shape.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/PolygonShapeConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/PulleyJointConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/WorldManifold.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/PositionSolverManifold.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/ConvexHull.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/Velocity.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/Distance.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/ChainShapeConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/RevoluteJointConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/PrismaticJointConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/WorldMisc.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/CodeDumper.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/VelocityConstraint.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/DistanceJointConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/World.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/MassData.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/ShapeSeparation.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/DistanceConf.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/PointStates.cpp
	${DORA_SOURCE_ROOT}/3rdParty/playrho/d2/part/Compositor.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/inflate.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/compress.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/deflate.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/gzread.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/crc32.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/zutil.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/gzlib.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/inftrees.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/uncompr.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/gzwrite.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/trees.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/gzclose.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/inffast.c
	${DORA_SOURCE_ROOT}/3rdParty/Zip/zlib/adler32.c
	${DORA_SOURCE_ROOT}/3rdParty/yoga/YGNodeStyle.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/YGPixelGrid.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/YGEnums.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/YGValue.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/YGConfig.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/YGNode.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/YGNodeLayout.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/config/Config.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/algorithm/AbsoluteLayout.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/algorithm/CalculateLayout.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/algorithm/PixelGrid.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/algorithm/Cache.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/algorithm/Baseline.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/algorithm/FlexLine.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/node/LayoutResults.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/node/Node.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/event/event.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/debug/Log.cpp
	${DORA_SOURCE_ROOT}/3rdParty/yoga/debug/AssertFatal.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/bgfxrenderer.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.RectF.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.ResourceManager.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.CurveLoader.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.IntrusiveList.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.EffectNodeRoot.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.Effect.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.WorkerThread.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.Manager.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.EffectNode.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.EffectNodeModel.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.EffectNodeTrack.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.FCurves.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.EffectNodeRing.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.InternalScript.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.DefaultEffectLoader.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.DefaultFile.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.Setting.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.InstanceGlobal.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.EffectNodeSprite.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.InstanceGroup.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.Resource.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.EffectNodeRibbon.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.Instance.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.Matrix43.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.Matrix44.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.InstanceContainer.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.Vector3D.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.Color.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.Vector2D.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.Random.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Effekseer.InstanceChunk.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/EffekseerRenderer.TrackRendererBase.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/EffekseerRenderer.RenderStateBase.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/VertexBuffer.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/GraphicsDeviceCPU.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/EffekseerRenderer.RibbonRendererBase.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/TextureLoader.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/EffekseerRenderer.Renderer.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/EffekseerRenderer.DDSTextureLoader.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/ModelLoader.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/EffekseerRenderer.ModelRendererBase.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/EffekseerRenderer.RingRendererBase.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/EffekseerRenderer.TGATextureLoader.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/EffekseerRenderer.Renderer_Impl.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/EffekseerRenderer.SpriteRendererBase.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/EffekseerRenderer.CommonUtils.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/EffekseerRenderer.PngTextureLoader.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/EffekseerRendererCommon/EffekseerRenderer.GpuParticles.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/ForceField/ForceFields.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Network/Effekseer.Server.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Network/Effekseer.Client.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Network/Effekseer.Session.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Network/Effekseer.Socket.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/IO/Effekseer.EfkEfcFactory.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/SIMD/Utils.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/SIMD/Mat44f.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/SIMD/Mat43f.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Utils/Effekseer.CustomAllocator.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/VectorField/VectorField.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/VectorField/VectorFieldLoader.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Noise/CurlNoise.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Model/ModelLoader.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Model/SplineGenerator.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Model/Model.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Model/ProceduralModelGenerator.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Model/PointCacheGenerator.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Parameter/Easing.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Parameter/Effekseer.Parameters.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Parameter/GpuParticlesParameter.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Parameter/Collisions.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Parameter/KillRules.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Parameter/Rotation.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Material/Effekseer.MaterialFile.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Material/Effekseer.MaterialCompiler.cpp
	${DORA_SOURCE_ROOT}/3rdParty/Effekseer/Effekseer/Material/Effekseer.CompiledMaterial.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tmxlite/LayerGroup.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tmxlite/Tileset.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tmxlite/Property.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tmxlite/Object.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tmxlite/ObjectGroup.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tmxlite/FreeFuncs.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tmxlite/ObjectTypes.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tmxlite/TileLayer.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tmxlite/Map.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tmxlite/ImageLayer.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tmxlite/detail/pugixml.cpp
	${DORA_SOURCE_ROOT}/3rdParty/nfd/nfd_portal.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tic80/cart.c
	${DORA_SOURCE_ROOT}/3rdParty/tic80/tools.c
	${DORA_SOURCE_ROOT}/3rdParty/tic80/tic.c
	${DORA_SOURCE_ROOT}/3rdParty/tic80/zip.c
	${DORA_SOURCE_ROOT}/3rdParty/tic80/tilesheet.c
	${DORA_SOURCE_ROOT}/3rdParty/tic80/script.c
	${DORA_SOURCE_ROOT}/3rdParty/tic80/core/io.c
	${DORA_SOURCE_ROOT}/3rdParty/tic80/core/draw.c
	${DORA_SOURCE_ROOT}/3rdParty/tic80/core/core.c
	${DORA_SOURCE_ROOT}/3rdParty/tic80/core/sound.c
	${DORA_SOURCE_ROOT}/3rdParty/tic80/ext/png.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tic80/api/yue.cpp
	${DORA_SOURCE_ROOT}/3rdParty/tic80/api/lua.c
	${DORA_SOURCE_ROOT}/3rdParty/tic80/api/parse_note.c
	${DORA_SOURCE_ROOT}/3rdParty/tic80/api/luaapi.c
	${DORA_SOURCE_ROOT}/3rdParty/tic80/vendor/blip-buf/blip_wasm_host.cpp
)
