import {useEffect,useRef,useState} from 'react';
import './admin-models.css';

type Shared={id:string;label:string;model:string;providerId:string;enabled:boolean;version:number;pricing?:{inputNanoCnyPerMillion:string;outputNanoCnyPerMillion:string}};
type Scope={enabled:boolean;limit:number;active:number;amountLimit:string;spent:string;reserved:string;accountId?:string;apiId?:string};
type Detail={version:1;configuration:Shared;secret:{version:number;available:boolean};api:{enabled:boolean;limit:number;active:number}|null};
type Page={version:1;items:Shared[];nextCursor:string|null};
type AdminAccount={accountId:string;enabled:boolean;administrator:boolean;version:number};
class AdminModelError extends Error{constructor(readonly status:number){super('管理操作未能确认');}}
async function request(path:string,signal:AbortSignal,method:'GET'|'PUT'|'DELETE'='GET',body?:unknown):Promise<any>{
  const operation=AbortSignal.any([signal,AbortSignal.timeout(10000)]);operation.throwIfAborted();
  const response=await fetch(path,{method,credentials:'same-origin',cache:'no-store',redirect:'error',signal:operation,...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});
  if(!response.ok||!response.body)throw new AdminModelError(response.status);
  const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;
  try{for(;;){operation.throwIfAborted();const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>131072)throw new Error('管理响应过大');chunks.push(value);}}
  finally{await reader.cancel();reader.releaseLock();}
  const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}
  return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));
}
const toNano=(value:string):string|null=>{
  if(!/^(?:0|[1-9][0-9]{0,9})(?:\.[0-9]{1,9})?$/.test(value))return null;
  const [whole='0',part='']=value.split('.');return (BigInt(whole)*1000000000n+BigInt((part+'000000000').slice(0,9))).toString();
};
const yuan=(nano:string)=>{try{const value=BigInt(nano),whole=value/1000000000n,part=(value%1000000000n).toString().padStart(9,'0').replace(/0+$/,'');return `¥${whole}${part?'.'+part:''}`;}catch{return '金额不可读取';}};
const validShared=(row:any):row is Shared=>Boolean(row&&/^[A-Za-z0-9_-]{1,128}$/.test(row.id)&&typeof row.label==='string'&&typeof row.model==='string'&&typeof row.enabled==='boolean'&&Number.isSafeInteger(row.version));
function decodePage(value:any):Page{if(value?.version!==1||!Array.isArray(value.items)||value.items.length>50||value.nextCursor!==null&&typeof value.nextCursor!=='string'||value.items.some((row:any)=>!validShared(row)))throw new Error('共享配置列表无效');return value;}
function decodeDetail(value:any):Detail{if(value?.version!==1||!validShared(value.configuration)||!value.secret||typeof value.secret.available!=='boolean'||!Number.isSafeInteger(value.secret.version)||value.api!==null&&(!value.api||typeof value.api.enabled!=='boolean'||!Number.isSafeInteger(value.api.limit)))throw new Error('共享配置详情无效');return value;}

export function AdminModelsEntry({accountId}:{accountId:string}){
  const [allowed,setAllowed]=useState(false),[open,setOpen]=useState(false);
  useEffect(()=>{let active=true;const controller=new AbortController();void request('/api/admin/shared-models?limit=1',controller.signal).then(value=>{decodePage(value);if(active)setAllowed(true);},()=>{if(active)setAllowed(false);});return()=>{active=false;controller.abort();};},[accountId]);
  return <>{allowed&&<button onClick={()=>setOpen(true)}>共享 API 管理</button>}{open&&<AdminModelsDialog onClose={()=>setOpen(false)}/>}</>;
}
function AdminModelsDialog({onClose}:{onClose:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null),[tab,setTab]=useState<'pool'|'allowance'>('pool');
  useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
  return <dialog ref={dialog} className="model-settings-dialog admin-model-dialog" aria-label="共享 API 管理" onCancel={event=>{event.preventDefault();onClose();}}><header><h2>共享 API 管理</h2><button autoFocus onClick={onClose}>关闭共享 API 管理</button></header><nav aria-label="共享 API 管理分类"><button aria-pressed={tab==='pool'} onClick={()=>setTab('pool')}>共享配置池</button><button aria-pressed={tab==='allowance'} onClick={()=>setTab('allowance')}>账号与逐 API 授权</button></nav>{tab==='pool'?<SharedPool/>:<SharedAllowances/>}</dialog>;
}
function SharedPool(){
  const [page,setPage]=useState<Page>(),[after,setAfter]=useState(''),[refresh,setRefresh]=useState(0),[failed,setFailed]=useState(false),[selected,setSelected]=useState(''),[creating,setCreating]=useState(false);
  useEffect(()=>{let active=true;const controller=new AbortController();setPage(undefined);setFailed(false);void request(`/api/admin/shared-models?limit=20&after=${encodeURIComponent(after)}`,controller.signal).then(value=>{if(active)setPage(decodePage(value));},()=>{if(active)setFailed(true);});return()=>{active=false;controller.abort();};},[after,refresh]);
  return <div className="admin-model-body"><p>先保存模型与人民币单价，再单独导入密钥和配置 API 全局并发。三项齐备后才能启用；共享 Key 不进入创作者浏览器。</p><div className="admin-model-toolbar"><button onClick={()=>{setCreating(value=>!value);setSelected('');}}>{creating?'关闭导入表单':'导入共享 API 配置'}</button><button onClick={()=>setRefresh(value=>value+1)}>刷新配置池</button></div>{creating&&<CreateShared onCreated={id=>{setCreating(false);setSelected(id);setAfter('');setRefresh(value=>value+1);}}/>}
    {!page?<p role="status">{failed?'共享配置暂时无法读取，请核对管理权限。':'正在读取共享配置…'}</p>:<><div className="admin-model-list">{page.items.map(row=><button key={row.id} aria-pressed={selected===row.id} onClick={()=>{setSelected(row.id);setCreating(false);}}><strong>{row.label}</strong><span>{row.model} · {row.enabled?'已启用':'已停用'}</span></button>)}</div>{!page.items.length&&<p>本页暂无共享配置。</p>}<div className="admin-model-toolbar">{after&&<button onClick={()=>setAfter('')}>返回首页</button>}{page.nextCursor&&<button onClick={()=>setAfter(page.nextCursor!)}>下一页</button>}</div></>}
    {selected&&<SharedDetail key={selected} id={selected} onChanged={()=>setRefresh(value=>value+1)}/>}</div>;
}
function CreateShared({onCreated}:{onCreated:(id:string)=>void}){
  const [providers,setProviders]=useState<{id:string;label:string}[]>(),[label,setLabel]=useState(''),[model,setModel]=useState(''),[providerId,setProviderId]=useState(''),[inputPrice,setInputPrice]=useState(''),[outputPrice,setOutputPrice]=useState(''),[state,setState]=useState<'idle'|'saving'|'uncertain'>('idle');
  const pending=useRef(''),controller=useRef(new AbortController());
  useEffect(()=>{let active=true;void request('/api/byok/providers',controller.current.signal).then(value=>{if(value?.version!==1||!Array.isArray(value.providers))throw new Error('供应商列表无效');if(active)setProviders(value.providers);},()=>{if(active)setProviders([]);});return()=>{active=false;controller.current.abort();};},[]);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();const inNano=toNano(inputPrice),outNano=toNano(outputPrice);if(state!=='idle'||!label.trim()||!model.trim()||!providerId||inNano===null||outNano===null)return;setState('saving');const id=crypto.randomUUID();pending.current=id;
    try{const result=await request(`/api/admin/shared-models/${id}`,controller.current.signal,'PUT',{expectedVersion:0,label:label.trim(),model:model.trim(),providerId,enabled:false,pricing:{inputNanoCnyPerMillion:inNano,outputNanoCnyPerMillion:outNano}});if(result?.version!==1||result.configuration?.id!==id||result.configuration.version!==1)throw new Error('导入回执无效');onCreated(id);}catch{setState('uncertain');}};
  return <form className="admin-model-form" onSubmit={event=>void submit(event)}><h3>导入共享 API 配置</h3><label>配置名称<input value={label} maxLength={256} onChange={event=>setLabel(event.target.value)} disabled={state!=='idle'} placeholder="例如：默认创作模型"/></label><label>供应商<select aria-label="共享供应商" value={providerId} onChange={event=>setProviderId(event.target.value)} disabled={state!=='idle'}><option value="">请选择供应商</option>{providers?.map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>模型标识<input value={model} maxLength={256} onChange={event=>setModel(event.target.value)} disabled={state!=='idle'} placeholder="供应商模型 ID"/></label><div className="admin-model-prices"><label>输入单价 · ¥/百万 Token<input aria-label="输入单价" value={inputPrice} onChange={event=>setInputPrice(event.target.value)} disabled={state!=='idle'} inputMode="decimal" placeholder="例如 1.5"/></label><label>输出单价 · ¥/百万 Token<input aria-label="输出单价" value={outputPrice} onChange={event=>setOutputPrice(event.target.value)} disabled={state!=='idle'} inputMode="decimal" placeholder="例如 5"/></label></div><button className="primary" disabled={state!=='idle'||!label.trim()||!model.trim()||!providerId||toNano(inputPrice)===null||toNano(outputPrice)===null}>{state==='saving'?'正在保存…':'保存配置（默认停用）'}</button>{state==='uncertain'&&<p role="alert">未能确认导入，请在配置池刷新核对；本次 ID 为 {pending.current}，不要盲目重建。</p>}</form>;
}
function SharedDetail({id,onChanged}:{id:string;onChanged:()=>void}){
  const [detail,setDetail]=useState<Detail>(),[failed,setFailed]=useState(false),[refresh,setRefresh]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[key,setKey]=useState(''),[limit,setLimit]=useState('0');
  const controller=useRef(new AbortController());
  useEffect(()=>{let active=true;const current=new AbortController();controller.current=current;setDetail(undefined);setFailed(false);void request(`/api/admin/shared-models/${id}`,current.signal).then(value=>{const next=decodeDetail(value);if(active){setDetail(next);setLimit(String(next.api?.limit??0));}},()=>{if(active)setFailed(true);});return()=>{active=false;current.abort();};},[id,refresh]);
  const act=async(work:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await work();setRefresh(value=>value+1);onChanged();}catch{setError('修改结果尚未确认，可能是版本冲突、权限变化或配置未就绪；请刷新详情核对，不要直接重试。');}finally{setBusy(false);}};
  if(!detail)return <p role="status">{failed?'无法读取配置详情，请刷新配置池。':'正在读取配置详情…'}</p>;
  const config=detail.configuration,pricing=config.pricing;
  return <section className="admin-model-detail"><div className="admin-model-toolbar"><h3>{config.label}</h3><button onClick={()=>setRefresh(value=>value+1)} disabled={busy}>刷新详情</button></div><p>{config.model} · {config.enabled?'已启用':'已停用'} · 配置 v{config.version}</p><p>输入 {pricing?yuan(pricing.inputNanoCnyPerMillion):'未定价'} / 百万 Token · 输出 {pricing?yuan(pricing.outputNanoCnyPerMillion):'未定价'} / 百万 Token</p><div className="admin-model-grid"><div><h4>共享密钥</h4><p>{detail.secret.available?'已加密托管':'尚未导入或已撤销'} · v{detail.secret.version}</p><label>导入/更换 API Key<input type="password" aria-label="共享 API Key" autoComplete="off" value={key} disabled={busy} onChange={event=>setKey(event.target.value)}/></label><button disabled={busy||!key.trim()} onClick={()=>{const value=key;setKey('');void act(()=>request(`/api/admin/shared-models/${id}/secret`,controller.current.signal,'PUT',{expectedVersion:detail.secret.version,key:value,consent:true}));}}>加密保存密钥</button><button disabled={busy||!detail.secret.available||config.enabled} onClick={()=>void act(()=>request(`/api/admin/shared-models/${id}/secret`,controller.current.signal,'DELETE',{expectedVersion:detail.secret.version}))}>撤销密钥</button><small>撤销前必须停用配置；密钥不会回显。</small></div><div><h4>API 全局并发</h4><p>{detail.api?`${detail.api.active}/${detail.api.limit} 正在使用 · ${detail.api.enabled?'已开放':'已停用'}`:'尚未配置'}</p><label>最大并发<input type="number" aria-label="API 最大并发" min={0} max={1000} value={limit} disabled={busy} onChange={event=>setLimit(event.target.value)}/></label><button disabled={busy||!Number.isSafeInteger(Number(limit))||Number(limit)<0||Number(limit)>1000} onClick={()=>void act(()=>request(`/api/admin/shared-models/${id}/limits`,controller.current.signal,'PUT',{enabled:Number(limit)>0,limit:Number(limit)}))}>保存 API 并发</button><small>账号总并发与逐 API 并发另在授权页控制。</small></div></div><div className="admin-model-toolbar"><button className="primary" disabled={busy||config.enabled||!detail.secret.available||!detail.api?.enabled||!detail.api.limit} onClick={()=>void act(()=>request(`/api/admin/shared-models/${id}`,controller.current.signal,'PUT',{expectedVersion:config.version,label:config.label,model:config.model,providerId:config.providerId,pricing:config.pricing,enabled:true}))}>启用共享配置</button><button disabled={busy||!config.enabled} onClick={()=>void act(()=>request(`/api/admin/shared-models/${id}`,controller.current.signal,'PUT',{expectedVersion:config.version,label:config.label,model:config.model,providerId:config.providerId,pricing:config.pricing,enabled:false}))}>停用共享配置</button></div>{error&&<p role="alert">{error}</p>}</section>;
}
function SharedAllowances(){
  const [account,setAccount]=useState(''),[confirmed,setConfirmed]=useState(''),[accountScope,setAccountScope]=useState<Scope>(),[grants,setGrants]=useState<{grantId:string;apiId:string;scope:Scope}[]>([]),[models,setModels]=useState<Shared[]>([]),[apiId,setApiId]=useState(''),[accountAmount,setAccountAmount]=useState(''),[accountLimit,setAccountLimit]=useState('1'),[grantAmount,setGrantAmount]=useState(''),[grantLimit,setGrantLimit]=useState('1'),[grantId,setGrantId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
  const [query,setQuery]=useState(''),[accounts,setAccounts]=useState<AdminAccount[]>([]),[searching,setSearching]=useState(true),[searchFailed,setSearchFailed]=useState(false),[selected,setSelected]=useState<string[]>([]);
  const [batchAccountAmount,setBatchAccountAmount]=useState('10'),[batchAccountLimit,setBatchAccountLimit]=useState('2'),[batchWithGrant,setBatchWithGrant]=useState(false),[batchApiId,setBatchApiId]=useState(''),[batchGrantAmount,setBatchGrantAmount]=useState('5'),[batchGrantLimit,setBatchGrantLimit]=useState('1'),[batchResult,setBatchResult]=useState('');
  const controller=useRef(new AbortController());
  useEffect(()=>{let active=true;const current=new AbortController();controller.current=current;void request('/api/admin/shared-models?limit=50',current.signal).then(value=>{const page=decodePage(value);if(active)setModels(page.items);},()=>{if(active)setModels([]);});return()=>{active=false;current.abort();};},[]);
  useEffect(()=>{if(!confirmed)return;let active=true;const current=new AbortController();controller.current=current;setAccountScope(undefined);setGrants([]);
    void Promise.all([request(`/api/admin/model-accounts/${encodeURIComponent(confirmed)}`,current.signal).catch(error=>{if(error instanceof AdminModelError&&error.status===404)return null;throw error;}),request(`/api/admin/model-accounts/${encodeURIComponent(confirmed)}/grants?limit=50`,current.signal)]).then(([total,page])=>{if(!active)return;if(page?.version!==1||!Array.isArray(page.items))throw new Error('授权列表无效');setAccountScope(total?.scope);setGrants(page.items);setAccountAmount(total?.scope?yuan(total.scope.amountLimit).slice(1):'');setAccountLimit(String(total?.scope?.limit??1));},()=>{if(active)setError('无法读取该账号的授权，请核对账号与管理权限。');});
    return()=>{active=false;current.abort();};},[confirmed,refresh]);
  useEffect(()=>{const row=grants.find(item=>item.apiId===apiId);setGrantId(row?.grantId??'');setGrantAmount(row?yuan(row.scope.amountLimit).slice(1):'');setGrantLimit(String(row?.scope.limit??1));},[apiId,grants]);
  useEffect(()=>{let active=true;const current=new AbortController();setSearching(true);setSearchFailed(false);const timer=setTimeout(()=>{void request(`/api/admin/accounts?limit=50&q=${encodeURIComponent(query.trim())}`,current.signal).then(value=>{if(value?.version!==1||!Array.isArray(value.items))throw new Error('账号搜索结果无效');const rows=value.items as AdminAccount[];if(rows.some(row=>!row||typeof row.accountId!=='string'||typeof row.enabled!=='boolean'||typeof row.administrator!=='boolean'||!Number.isSafeInteger(row.version)))throw new Error('账号搜索结果无效');if(active)setAccounts(rows);},()=>{if(active){setAccounts([]);setSearchFailed(true);}}).finally(()=>{if(active)setSearching(false);});},250);return()=>{active=false;clearTimeout(timer);current.abort();};},[query,refresh]);
  const lookup=async()=>{if(!account.trim()||busy)return;setBusy(true);setError('');try{const result=await request(`/api/admin/accounts/${encodeURIComponent(account.trim())}`,controller.current.signal);if(result?.accountId!==account.trim())throw new Error('账号回执无效');setConfirmed(account.trim());setRefresh(value=>value+1);}catch{setError('未能核实这个受邀账号，请检查账号名或管理权限。');}finally{setBusy(false);}};
  const saveAccount=async()=>{const nano=toNano(accountAmount);if(!confirmed||nano===null||busy)return;setBusy(true);setError('');try{await request(`/api/admin/model-accounts/${encodeURIComponent(confirmed)}`,controller.current.signal,'PUT',{enabled:Number(accountLimit)>0,limit:Number(accountLimit),amountLimit:nano});setRefresh(value=>value+1);}catch{setError('账号额度未能确认，请刷新核对，不要直接重复提交。');}finally{setBusy(false);}};
  const saveGrant=async()=>{const nano=toNano(grantAmount);if(!confirmed||!apiId||nano===null||busy)return;setBusy(true);setError('');const id=grantId||crypto.randomUUID();setGrantId(id);try{await request(`/api/admin/model-grants/${id}`,controller.current.signal,'PUT',{accountId:confirmed,apiId,enabled:Number(grantLimit)>0,limit:Number(grantLimit),amountLimit:nano});setRefresh(value=>value+1);}catch{setError(`逐 API 授权未能确认；请刷新账号授权核对 ID ${id}，不要新建另一条。`);}finally{setBusy(false);}};
  const toggleSelected=(id:string)=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
  const batchValid=selected.length>0&&toNano(batchAccountAmount)!==null&&Number.isSafeInteger(Number(batchAccountLimit))&&Number(batchAccountLimit)>=0&&Number(batchAccountLimit)<=1000&&(!batchWithGrant||Boolean(batchApiId)&&toNano(batchGrantAmount)!==null&&Number.isSafeInteger(Number(batchGrantLimit))&&Number(batchGrantLimit)>=0&&Number(batchGrantLimit)<=1000);
  const saveBatch=async()=>{const accountNano=toNano(batchAccountAmount),grantNano=toNano(batchGrantAmount);if(!batchValid||accountNano===null||busy)return;setBusy(true);setError('');setBatchResult('');try{const result=await request('/api/admin/model-allowances/batch',controller.current.signal,'PUT',{accountIds:selected,account:{enabled:Number(batchAccountLimit)>0,limit:Number(batchAccountLimit),amountLimit:accountNano},...(batchWithGrant&&grantNano!==null?{grant:{apiId:batchApiId,enabled:Number(batchGrantLimit)>0,limit:Number(batchGrantLimit),amountLimit:grantNano}}:{})});if(result?.version!==1||!Array.isArray(result.items)||result.items.length!==selected.length)throw new Error('批量回执无效');setBatchResult(`已为 ${selected.length} 个账号统一保存额度${batchWithGrant?'和逐 API 授权':''}。`);setRefresh(value=>value+1);}catch{setError('批量设置未能确认。该操作由服务端原子提交，不会只修改其中一部分；请刷新后核对。');}finally{setBusy(false);}};
  return <div className="admin-model-body allowance-workspace">
    <div className="allowance-intro"><div><strong>用户额度</strong><p>搜索并选择账号后，可统一设置账号总额度；也可以同时批量分配一个共享 API。金额累计不自动重置，所有调整都会留下审计记录。</p></div><span>{selected.length} 个已选择</span></div>
    <section className="allowance-card account-picker" aria-label="搜索和选择额度账号">
      <div className="allowance-card-heading"><div><span className="step-badge">1</span><h3>选择用户</h3></div><button disabled={!selected.length} onClick={()=>setSelected([])}>清空选择</button></div>
      <label className="account-search">搜索账号<input aria-label="搜索额度账号" type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="输入账号名的一部分"/></label>
      <div className="account-picker-actions"><button disabled={!accounts.length} onClick={()=>setSelected(current=>Array.from(new Set([...current,...accounts.map(row=>row.accountId)])))}>选择当前结果</button><span>{searching?'正在搜索…':searchFailed?'账号搜索失败，请重试':`找到 ${accounts.length} 个账号`}</span></div>
      <div className="allowance-account-list">{accounts.map(row=><div key={row.accountId} className={selected.includes(row.accountId)?'selected':''}><label><input type="checkbox" checked={selected.includes(row.accountId)} onChange={()=>toggleSelected(row.accountId)}/><span><strong>{row.accountId}</strong><small>{row.administrator?'管理员':'创作者'} · {row.enabled?'已启用':'已停用'}</small></span></label><button onClick={()=>{setAccount(row.accountId);setConfirmed(row.accountId);setRefresh(value=>value+1);}}>单独设置</button></div>)}</div>
      {!searching&&!accounts.length&&!searchFailed&&<p className="empty-state">没有匹配账号，请尝试更短的关键词。</p>}
      <div className="exact-account-lookup"><label>按准确账号名定位<input aria-label="授权账号名" value={account} onChange={event=>setAccount(event.target.value)} placeholder="完整账号名"/></label><button disabled={busy||!account.trim()} onClick={()=>void lookup()}>读取账号授权</button></div>
    </section>
    <section className="allowance-card batch-allowance" aria-label="批量设置用户额度">
      <div className="allowance-card-heading"><div><span className="step-badge">2</span><h3>批量额度模板</h3></div><span>将应用到 {selected.length} 个账号</span></div>
      <div className="admin-model-prices"><label>账号累计金额上限 · ¥<input aria-label="批量账号金额上限" value={batchAccountAmount} onChange={event=>setBatchAccountAmount(event.target.value)} inputMode="decimal"/></label><label>账号模型并发<input aria-label="批量账号模型并发" type="number" min={0} max={1000} value={batchAccountLimit} onChange={event=>setBatchAccountLimit(event.target.value)}/></label></div>
      <label className="batch-grant-toggle"><input type="checkbox" checked={batchWithGrant} onChange={event=>setBatchWithGrant(event.target.checked)}/> 同时为这些账号设置逐 API 额度</label>
      {batchWithGrant&&<div className="batch-grant-fields"><label>共享 API<select aria-label="批量授权 API" value={batchApiId} onChange={event=>setBatchApiId(event.target.value)}><option value="">请选择配置</option>{models.map(row=><option key={row.id} value={row.id}>{row.label} · {row.enabled?'可用':'停用'}</option>)}</select></label><div className="admin-model-prices"><label>逐 API 累计金额上限 · ¥<input aria-label="批量逐 API 金额上限" value={batchGrantAmount} onChange={event=>setBatchGrantAmount(event.target.value)} inputMode="decimal"/></label><label>逐 API 并发<input aria-label="批量逐 API 并发" type="number" min={0} max={1000} value={batchGrantLimit} onChange={event=>setBatchGrantLimit(event.target.value)}/></label></div></div>}
      <div className="batch-submit"><button className="primary" disabled={busy||!batchValid} onClick={()=>void saveBatch()}>{busy?'正在保存…':`应用到 ${selected.length} 个账号`}</button><small>批量操作由服务端一次性提交；任一账号无效时整批不会生效。</small></div>{batchResult&&<p role="status" className="success-message">{batchResult}</p>}
    </section>
    {confirmed&&<section className="allowance-card individual-allowance" aria-label={`单独设置 ${confirmed} 的额度`}><div className="allowance-card-heading"><div><span className="step-badge">3</span><h3>{confirmed}</h3></div><button onClick={()=>setConfirmed('')}>关闭单独设置</button></div><p>{accountScope?`已用 ${yuan(accountScope.spent)} · 暂留 ${yuan(accountScope.reserved)} · 并发 ${accountScope.active}/${accountScope.limit}`:'尚未分配账号模型额度'}</p><div className="admin-model-prices"><label>累计金额上限 · ¥<input aria-label="账号金额上限" value={accountAmount} onChange={event=>setAccountAmount(event.target.value)} inputMode="decimal"/></label><label>账号模型并发<input aria-label="账号模型并发" type="number" min={0} max={1000} value={accountLimit} onChange={event=>setAccountLimit(event.target.value)}/></label></div><button disabled={busy||toNano(accountAmount)===null||!Number.isSafeInteger(Number(accountLimit))||Number(accountLimit)<0||Number(accountLimit)>1000} onClick={()=>void saveAccount()}>保存账号总额度</button><div className="individual-grant"><h4>逐 API 授权</h4><label>共享 API<select aria-label="选择授权 API" value={apiId} onChange={event=>setApiId(event.target.value)}><option value="">请选择配置</option>{models.map(row=><option key={row.id} value={row.id}>{row.label} · {row.enabled?'可用':'停用'}</option>)}</select></label>{apiId&&<><p>{grantId?`已有授权 ${grantId}`:'尚未授权此 API；保存后创建独立授权 ID。'}</p><div className="admin-model-prices"><label>此 API 累计金额上限 · ¥<input aria-label="逐 API 金额上限" value={grantAmount} onChange={event=>setGrantAmount(event.target.value)} inputMode="decimal"/></label><label>此账号可用 API 并发<input aria-label="逐 API 并发" type="number" min={0} max={1000} value={grantLimit} onChange={event=>setGrantLimit(event.target.value)}/></label></div><button disabled={busy||!accountScope||toNano(grantAmount)===null||!Number.isSafeInteger(Number(grantLimit))||Number(grantLimit)<0||Number(grantLimit)>1000} onClick={()=>void saveGrant()}>{grantId?'调整逐 API 授权':'分配逐 API 授权'}</button></>}</div></section>}
    {error&&<p role="alert">{error}</p>}
  </div>;
}
