matrix:
  include:
  - language: c++
    os: osx
    osx_image: xcode10.1
    before_install: Tools/tolua++/build.sh
    script: xcodebuild -project Project/macOS/Dorothy.xcodeproj -target Dorothy
  - language: android
    os: osx
    android:
    components:
      - tools
      - platform-tools
      - extra-google-m2repository
      - extra-android-m2repository
    addons:
      apt_packages:
        - pandoc
    before_install:
      - brew install ant
      - Tools/tolua++/build.sh
    install:
      - echo y | sdkmanager "ndk-bundle"
      - echo y | sdkmanager "cmake;3.6.4111459"
      - echo y | sdkmanager "lldb;3.1"
    before_script:
      - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
    script:
      - ./Project/Android/gradlew -q assembleDebug

