matrix:
  include:
  - language: cpp
    os: osx
    osx_image: xcode10.1
    before_install: Tools/tolua++/build.sh
    script: xcodebuild -project Project/macOS/Dorothy.xcodeproj -target Dorothy
  - language: cpp
    os: osx
    osx_image: xcode10.1
    before_install: Tools/tolua++/build.sh
    script: xcodebuild -project Project/iOS/Dorothy.xcodeproj -configuration debug -target Dorothy -arch x86_64 -sdk iphonesimulator12.1
  - language: android
    dist: trusty
    sudo: true
    android:
    components:
      - tools
      - platform-tools
      - build-tools-29.0.1
      - android-26
      - extra-google-m2repository
      - extra-android-m2repository
    addons:
      apt_packages:
        - pandoc
    licenses:
      - 'android-sdk-license-.+'
      - '.+'
    before_install:
      - sudo apt-get install ant
      - sudo apt-get install lua5.1
      - sudo apt-get install -y luarocks
      - sudo luarocks install luafilesystem
      - cd ./Tools/tolua++
      - lua tolua++.lua
    install:
      - yes | ${ANDROID_HOME}/tools/bin/sdkmanager "ndk-bundle"
      - yes | ${ANDROID_HOME}/tools/bin/sdkmanager "cmake;3.6.4111459"
      - yes | ${ANDROID_HOME}/tools/bin/sdkmanager "lldb;3.1"
    before_script:
      - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
    script:
      - cd ../../Project/Android
      - ./gradlew assemble

