matrix:
  include:
  - language: c++
    osx_image: xcode10.1
    before_install: Tools/tolua++/build.sh
    script: xcodebuild -project Project/macOS/Dorothy.xcodeproj -target Dorothy
  - language: android
    android:
      components:
        - tools
        - platform-tools
        - tools
        - build-tools-26.1.1
        - android-26
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-android-support
        - extra-google-google_play_services
        - add-on
        - extra
      install:
        - echo y | sdkmanager "ndk-bundle"
        - echo y | sdkmanager "cmake;3.6.4111459"
        - echo y | sdkmanager "lldb;3.1"
      before_script:
        - wget https://dl.google.com/android/repository/android-ndk-r19-linux-x86_64.zip
        - unzip -qq android-ndk-r19-linux-x86_64.zip
        - export ANDROID_NDK_HOME=`pwd`/android-ndk-r16b
        - export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
        - export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64"
        - export PATH=$PATH:${ANDROID_NDK_HOME}
        - env
      script:
        - ./gradlew build
