matrix:
  include:
  - language: cpp
    os: osx
    osx_image: xcode10.1
    before_install: Tools/tolua++/build.sh
    xcode_project: Project/macOS/Dorothy.xcodeproj
    xcode_scheme: Dorothy
    xcode_destination: platform=macOS
  - language: cpp
    os: osx
    osx_image: xcode10.1
    before_install: Tools/tolua++/build.sh
    xcode_project: Project/iOS/Dorothy.xcodeproj
    xcode_scheme: Dorothy
    xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
  - language: android
    sudo: true
    android:
    components:
      - tools
      - platform-tools
      - extra-google-m2repository
      - extra-android-m2repository
    addons:
      apt_packages:
        - pandoc
    before_install:
      - sudo apt-get install ant
      - sudo apt-get install lua5.1
      - sudo apt-get install -y luarocks
      - sudo luarocks install luafilesystem
      - cd ./Tools/tolua++
      - lua tolua++.lua
    install:
      - echo y | sdkmanager "ndk-bundle"
      - echo y | sdkmanager "cmake;3.6.4111459"
      - echo y | sdkmanager "lldb;3.1"
    before_script:
      - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
    script:
      - cd ../../Project/Android
      - ./gradlew assemble

