jobs:
  include:
  - language: cpp
    os: osx
    osx_image: xcode11.3
    before_install: Tools/tolua++/build.sh
    script: xcodebuild -project Project/macOS/Dorothy.xcodeproj -target Dorothy
  - language: cpp
    os: osx
    osx_image: xcode11.3
    before_install: Tools/tolua++/build.sh
    script: xcodebuild -project Project/iOS/Dorothy.xcodeproj -configuration debug -target Dorothy -arch x86_64 -sdk iphonesimulator13.2
  - language: android
    dist: trusty
    android:
      components:
        - tools
        - platform-tools
        - build-tools-30.0.0-preview
        - android-26
        - extra-google-m2repository
        - extra-android-m2repository
      licenses:
        - 'android-sdk-license-.+'
        - '.+'
    before_install:
      - sudo apt-get install ant
      - sudo apt-get install lua5.1
      - sudo apt-get install -y luarocks
      - sudo luarocks install luafilesystem
      - cd ./Tools/tolua++
      - lua tolua++.lua
    install:
      - yes | sdkmanager "ndk;21.0.6113669"
      - yes | sdkmanager "cmake;3.10.2.4988404"
      - yes | sdkmanager "lldb;3.1"
    script:
      - cd ../../Project/Android
      - ./gradlew assemble

