-- Portable Web support lists. Native engine sources remain in manifests/engine.lua.
function main()
    return {
        love = {
            "Source/3rdParty/Love/src/modules/physics/box2d/*.cpp",
            "Source/3rdParty/Love/src/libraries/Box2D/**.cpp",
            "Source/3rdParty/Love/src/common/Object.cpp",
            "Source/3rdParty/Love/src/common/types.cpp",
            "Source/3rdParty/Love/src/common/Reference.cpp",
            "Source/3rdParty/Love/src/common/Module.cpp",
            "Source/3rdParty/Love/src/common/Exception.cpp",
            "Source/3rdParty/Love/src/common/deprecation.cpp",
            "Source/3rdParty/Love/src/common/runtime.cpp",
            "Source/3rdParty/Love/src/common/Matrix.cpp",
            "Source/3rdParty/Love/src/common/Data.cpp",
            "Source/3rdParty/Love/src/common/Variant.cpp",
            "Source/3rdParty/Love/src/common/StringMap.cpp",
            "Source/3rdParty/Love/src/common/b64.cpp",
            "Source/3rdParty/Love/src/common/pixelformat.cpp",
            "Source/3rdParty/Love/src/libraries/lz4/lz4.c",
            "Source/3rdParty/Love/src/libraries/lz4/lz4hc.c",
            "Source/3rdParty/Love/src/libraries/noise1234/noise1234.cpp",
            "Source/3rdParty/Love/src/libraries/noise1234/simplexnoise1234.cpp",
            "Source/3rdParty/Love/src/modules/math/BezierCurve.cpp",
            "Source/3rdParty/Love/src/modules/math/wrap_BezierCurve.cpp",
            "Source/3rdParty/Love/src/modules/math/MathModule.cpp",
            "Source/3rdParty/Love/src/modules/math/wrap_Math.cpp",
            "Source/3rdParty/Love/src/modules/math/RandomGenerator.cpp",
            "Source/3rdParty/Love/src/modules/math/wrap_RandomGenerator.cpp",
            "Source/3rdParty/Love/src/modules/math/Transform.cpp",
            "Source/3rdParty/Love/src/modules/math/wrap_Transform.cpp",
            "Source/3rdParty/Love/src/modules/data/ByteData.cpp",
            "Source/3rdParty/Love/src/modules/data/CompressedData.cpp",
            "Source/3rdParty/Love/src/modules/data/Compressor.cpp",
            "Source/3rdParty/Love/src/modules/data/DataModule.cpp",
            "Source/3rdParty/Love/src/modules/data/DataView.cpp",
            "Source/3rdParty/Love/src/modules/data/HashFunction.cpp",
            "Source/3rdParty/Love/src/modules/data/wrap_ByteData.cpp",
            "Source/3rdParty/Love/src/modules/data/wrap_CompressedData.cpp",
            "Source/3rdParty/Love/src/modules/data/wrap_Data.cpp",
            "Source/3rdParty/Love/src/modules/data/wrap_DataModule.cpp",
            "Source/3rdParty/Love/src/modules/data/wrap_DataView.cpp",
            "Source/3rdParty/Love/src/modules/audio/Filter.cpp",
            "Source/3rdParty/Love/src/modules/audio/Source.cpp",
            "Source/3rdParty/Love/src/modules/audio/wrap_Source.cpp",
            "Source/3rdParty/Love/src/modules/event/Event.cpp",
            "Source/3rdParty/Love/src/modules/event/wrap_Event.cpp",
            "Source/3rdParty/Love/src/modules/window/Window.cpp",
            "Source/3rdParty/Love/src/modules/window/wrap_Window.cpp",
            "Source/3rdParty/Love/src/modules/keyboard/Keyboard.cpp",
            "Source/3rdParty/Love/src/modules/keyboard/wrap_Keyboard.cpp",
            "Source/3rdParty/Love/src/modules/mouse/Cursor.cpp",
            "Source/3rdParty/Love/src/modules/mouse/wrap_Cursor.cpp",
            "Source/3rdParty/Love/src/modules/mouse/wrap_Mouse.cpp",
            "Source/3rdParty/Love/src/modules/touch/wrap_Touch.cpp",
            "Source/3rdParty/Love/src/modules/joystick/Joystick.cpp",
            "Source/3rdParty/Love/src/modules/joystick/wrap_Joystick.cpp",
            "Source/3rdParty/Love/src/modules/joystick/wrap_JoystickModule.cpp",
            "Source/3rdParty/Love/src/modules/physics/Body.cpp",
            "Source/3rdParty/Love/src/modules/physics/Shape.cpp",
            "Source/3rdParty/Love/src/modules/physics/Joint.cpp",
            "Source/3rdParty/Love/src/modules/filesystem/File.cpp",
            "Source/3rdParty/Love/src/modules/filesystem/FileData.cpp",
            "Source/3rdParty/Love/src/modules/filesystem/Filesystem.cpp",
            "Source/3rdParty/Love/src/modules/filesystem/wrap_File.cpp",
            "Source/3rdParty/Love/src/modules/filesystem/wrap_FileData.cpp",
            "Source/3rdParty/Love/src/modules/filesystem/wrap_Filesystem.cpp",
            "Source/3rdParty/Love/src/modules/font/GlyphData.cpp",
            "Source/3rdParty/Love/src/modules/font/Rasterizer.cpp",
            "Source/3rdParty/Love/src/modules/font/TrueTypeRasterizer.cpp",
            "Source/3rdParty/Love/src/modules/font/wrap_Font.cpp",
            "Source/3rdParty/Love/src/modules/font/wrap_GlyphData.cpp",
            "Source/3rdParty/Love/src/modules/font/wrap_Rasterizer.cpp",
            "Source/3rdParty/Love/src/modules/graphics/Drawable.cpp",
            "Source/3rdParty/Love/src/modules/graphics/vertex.cpp",
            "Source/3rdParty/Love/src/modules/graphics/Font.cpp",
            "Source/3rdParty/Love/src/modules/graphics/Shader.cpp",
            "Source/3rdParty/Love/src/modules/graphics/Text.cpp",
            "Source/3rdParty/Love/src/modules/graphics/Video.cpp",
            "Source/3rdParty/Love/src/modules/graphics/Mesh.cpp",
            "Source/3rdParty/Love/src/modules/graphics/SpriteBatch.cpp",
            "Source/3rdParty/Love/src/modules/graphics/ParticleSystem.cpp",
            "Source/3rdParty/Love/src/modules/graphics/depthstencil.cpp",
            "Source/3rdParty/Love/src/modules/graphics/Texture.cpp",
            "Source/3rdParty/Love/src/modules/graphics/Canvas.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_Canvas.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsCanvasConstructor.cpp",
            "Source/3rdParty/Love/src/modules/graphics/Image.cpp",
            "Source/3rdParty/Love/src/modules/graphics/Quad.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_Texture.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsDraw.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsDisplayState.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsCapabilities.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsInfo.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsImageConstructor.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsScreenshot.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsFontState.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsFontConstructor.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsPrimitives.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsPrint.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsQuad.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsShaderConstructor.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsState.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_GraphicsShaderState.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_Image.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_Font.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_Shader.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_Text.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_Video.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_Mesh.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_SpriteBatch.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_ParticleSystem.cpp",
            "Source/3rdParty/Love/src/modules/graphics/wrap_Quad.cpp",
            "Source/3rdParty/Love/src/modules/image/ImageDataBase.cpp",
            "Source/3rdParty/Love/src/modules/image/CompressedSlice.cpp",
            "Source/3rdParty/Love/src/modules/image/CompressedImageData.cpp",
            "Source/3rdParty/Love/src/modules/image/FormatHandler.cpp",
            "Source/3rdParty/Love/src/modules/image/Image.cpp",
            "Source/3rdParty/Love/src/modules/image/ImageData.cpp",
            "Source/3rdParty/Love/src/modules/image/wrap_Image.cpp",
            "Source/3rdParty/Love/src/modules/image/wrap_ImageData.cpp",
            "Source/3rdParty/Love/src/modules/image/wrap_CompressedImageData.cpp",
            "Source/3rdParty/Love/src/modules/sound/Decoder.cpp",
            "Source/3rdParty/Love/src/modules/sound/Sound.cpp",
            "Source/3rdParty/Love/src/modules/sound/SoundData.cpp",
            "Source/3rdParty/Love/src/modules/sound/wrap_Decoder.cpp",
            "Source/3rdParty/Love/src/modules/sound/wrap_Sound.cpp",
            "Source/3rdParty/Love/src/modules/sound/wrap_SoundData.cpp",
            "Source/3rdParty/Love/src/modules/system/System.cpp",
            "Source/3rdParty/Love/src/modules/system/wrap_System.cpp",
            "Source/3rdParty/Love/src/modules/timer/wrap_Timer.cpp",
            "Source/3rdParty/Love/src/modules/thread/Channel.cpp",
            "Source/3rdParty/Love/src/modules/thread/LuaThread.cpp",
            "Source/3rdParty/Love/src/modules/thread/wrap_Channel.cpp",
            "Source/3rdParty/Love/src/modules/thread/wrap_LuaThread.cpp",
            "Source/3rdParty/Love/src/modules/thread/wrap_ThreadModule.cpp",
            "Source/3rdParty/Love/src/modules/video/wrap_VideoStream.cpp",
        },
        link = {
            "Source/3rdParty/bgfx/src/bgfx.cpp",
            "Source/3rdParty/bgfx/src/debug_renderdoc.cpp",
            "Source/3rdParty/bgfx/src/glcontext_html5.cpp",
            "Source/3rdParty/bgfx/src/renderer_agc.cpp",
            "Source/3rdParty/bgfx/src/renderer_d3d11.cpp",
            "Source/3rdParty/bgfx/src/renderer_d3d12.cpp",
            "Source/3rdParty/bgfx/src/renderer_gl.cpp",
            "Source/3rdParty/bgfx/src/renderer_gnm.cpp",
            "Source/3rdParty/bgfx/src/renderer_noop.cpp",
            "Source/3rdParty/bgfx/src/renderer_nvn.cpp",
            "Source/3rdParty/bgfx/src/renderer_vk.cpp",
            "Source/3rdParty/bgfx/src/shader.cpp",
            "Source/3rdParty/bgfx/src/shader_dxbc.cpp",
            "Source/3rdParty/bgfx/src/shader_spirv.cpp",
            "Source/3rdParty/bgfx/src/topology.cpp",
            "Source/3rdParty/bgfx/src/vertexlayout.cpp",
            "Source/3rdParty/bgfx/dora/DoraShaderc.cpp",
            "Source/3rdParty/bgfx/tools/shaderc/shaderc.cpp",
            "Source/3rdParty/bgfx/tools/shaderc/shaderc_glsl.cpp",
            "Source/3rdParty/bgfx/tools/shaderc/shaderc_hlsl.cpp",
            "Source/3rdParty/bgfx/tools/shaderc/shaderc_metal.cpp",
            "Source/3rdParty/bgfx/tools/shaderc/shaderc_pssl.cpp",
            "Source/3rdParty/bgfx/tools/shaderc/shaderc_spirv.cpp",
            "Source/3rdParty/theora/TheoraSources.c",
        },
        probes = {
            {name = "dora-web-love-link-probe", source = "Projects/Web/LoveLinkProbe.cpp", output = "dora-love-runtime-probe", flags = {
                "--ignore-dynamic-linking",
                "--no-entry",
                "-fwasm-exceptions",
                "-sSUPPORT_LONGJMP=wasm",
                "-sUSE_SDL=2",
                "-sUSE_WEBGL2=1",
                "-sFULL_ES3=1",
                "-sALLOW_MEMORY_GROWTH=1",
                "-sSTACK_SIZE=8MB",
                "-sINITIAL_MEMORY=64MB",
                "-sMAXIMUM_MEMORY=1GB",
                "-sFILESYSTEM=1",
                "-sFETCH=1",
                "-sEXPORTED_FUNCTIONS=['_dora_web_love_link_probe','_dora_web_love_link_probe_error','_dora_web_love_incremental_probe_begin','_dora_web_love_incremental_probe_step','_dora_web_love_incremental_probe_steps']",
                "-sEXPORTED_RUNTIME_METHODS=['ccall','UTF8ToString']",
                "--preload-file @web@/demo-game/Font/web-fixture.ttf@/love-fixture.ttf",
                "--pre-js @web@/love-link-probe-runner.js",
            }},
            {name = "dora-web-love-graphics-probe", source = "Projects/Web/LoveGraphicsProbe.cpp", output = "dora-love-graphics-probe", flags = {
                "--ignore-dynamic-linking",
                "-fwasm-exceptions",
                "-sSUPPORT_LONGJMP=wasm",
                "-sUSE_SDL=2",
                "-sUSE_WEBGL2=1",
                "-sFULL_ES3=1",
                "-sALLOW_MEMORY_GROWTH=1",
                "-sSTACK_SIZE=8MB",
                "-sINITIAL_MEMORY=64MB",
                "-sMAXIMUM_MEMORY=1GB",
                "-sEXIT_RUNTIME=0",
                "-sFILESYSTEM=1",
                "-sFETCH=1",
                "-sEXPORTED_FUNCTIONS=['_main','_dora_web_stop','_dora_web_set_suspended','_dora_web_release_input','_dora_web_love_graphics_probe_start','_dora_web_love_graphics_probe_status','_dora_web_love_graphics_probe_release','_dora_web_love_graphics_probe_error']",
                "-sEXPORTED_RUNTIME_METHODS=['ccall','cwrap','UTF8ToString']",
                "--pre-js @web@/love-graphics-probe-runner.js",
                "--preload-file @root@/Assets/Script/Lib/lualib_bundle.lua@/game/Script/Lib/lualib_bundle.lua",
                "--preload-file @web@/love-graphics-fixture@/love-graphics",
                "--shell-file @web@/player-shell.html",
                "-sASSERTIONS=1",
                "--profiling-funcs",
            }},
            {name = "dora-web-love-shader-probe", source = "Projects/Web/LoveShaderProbe.cpp", output = "dora-love-shader-probe", flags = {
                "--ignore-dynamic-linking",
                "-fwasm-exceptions",
                "-sSUPPORT_LONGJMP=wasm",
                "-sUSE_SDL=2",
                "-sUSE_WEBGL2=1",
                "-sFULL_ES3=1",
                "-sALLOW_MEMORY_GROWTH=1",
                "-sSTACK_SIZE=8MB",
                "-sINITIAL_MEMORY=64MB",
                "-sMAXIMUM_MEMORY=1GB",
                "-sEXIT_RUNTIME=0",
                "-sFILESYSTEM=1",
                "-sFETCH=1",
                "-sEXPORTED_FUNCTIONS=['_main','_dora_web_stop','_dora_web_set_suspended','_dora_web_release_input','_dora_web_love_shader_probe_start','_dora_web_love_shader_probe_status','_dora_web_love_shader_probe_release','_dora_web_love_shader_probe_error']",
                "-sEXPORTED_RUNTIME_METHODS=['ccall','cwrap','UTF8ToString']",
                "--pre-js @web@/love-shader-probe-runner.js",
                "--preload-file @root@/Assets/Script/Lib/lualib_bundle.lua@/game/Script/Lib/lualib_bundle.lua",
                "--preload-file @root@/Assets/Shader/Love/varying.def.sc@/game/Shader/Love/varying.def.sc",
                "--preload-file @web@/love-shader-fixture@/love-shader",
                "--shell-file @web@/player-shell.html",
                "-sASSERTIONS=1",
                "--profiling-funcs",
            }},
            {name = "dora-web-love-audio-probe", source = "Projects/Web/LoveAudioProbe.cpp", output = "dora-love-audio-probe", flags = {
                "--ignore-dynamic-linking",
                "-fwasm-exceptions",
                "-sSUPPORT_LONGJMP=wasm",
                "-sUSE_SDL=2",
                "-sUSE_WEBGL2=1",
                "-sFULL_ES3=1",
                "-sALLOW_MEMORY_GROWTH=1",
                "-sSTACK_SIZE=8MB",
                "-sINITIAL_MEMORY=64MB",
                "-sMAXIMUM_MEMORY=1GB",
                "-sEXIT_RUNTIME=0",
                "-sFILESYSTEM=1",
                "-sFETCH=1",
                "-sEXPORTED_FUNCTIONS=['_main','_dora_web_stop','_dora_web_set_suspended','_dora_web_release_input','_dora_web_love_audio_probe_start','_dora_web_love_audio_probe_status','_dora_web_love_audio_probe_restart_first','_dora_web_love_audio_probe_release_first','_dora_web_love_audio_probe_release','_dora_web_love_audio_probe_instance_count','_dora_web_love_audio_probe_source_count','_dora_web_love_audio_probe_playing_count','_dora_web_love_audio_probe_audio_file_delta','_dora_web_love_audio_probe_voice_delta','_dora_web_love_audio_probe_frame','_dora_web_love_audio_probe_error']",
                "-sEXPORTED_RUNTIME_METHODS=['ccall','cwrap','UTF8ToString']",
                "--pre-js @web@/love-audio-probe-runner.js",
                "--preload-file @root@/Assets/Script/Lib/lualib_bundle.lua@/game/Script/Lib/lualib_bundle.lua",
                "--preload-file @out@/love-audio-fixture@/love-audio",
                "--shell-file @web@/player-shell.html",
                "-sASSERTIONS=1",
                "--profiling-funcs",
            }},
            {name = "dora-web-love-pthread-player", source = "Projects/Web/LovePthreadPlayer.cpp", output = "love-pthread-player", flags = {
                "--ignore-dynamic-linking",
                "-fwasm-exceptions",
                "-sSUPPORT_LONGJMP=wasm",
                "-sUSE_SDL=2",
                "-sUSE_WEBGL2=1",
                "-sFULL_ES3=1",
                "-sALLOW_MEMORY_GROWTH=1",
                "-sSTACK_SIZE=8MB",
                "-sINITIAL_MEMORY=64MB",
                "-sMAXIMUM_MEMORY=1GB",
                "-sEXIT_RUNTIME=0",
                "-sFILESYSTEM=1",
                "-sFETCH=1",
                "-lidbfs.js",
                "-sEXPORTED_FUNCTIONS=['_main','_dora_web_stop','_dora_web_set_suspended','_dora_web_release_input','_dora_web_love_player_start','_dora_web_love_player_status','_dora_web_love_player_stop','_dora_web_love_player_error','_dora_web_love_player_project']",
                "-sEXPORTED_RUNTIME_METHODS=['ccall','cwrap','UTF8ToString']",
                "--pre-js @web@/web-platform.js",
                "--pre-js @web@/web-package.js",
                "--pre-js @web@/love-pthread-player.js",
                "--pre-js @web@/web-loader.js",
                "--preload-file @root@/Assets/Script/Lib/lualib_bundle.lua@/game/Script/Lib/lualib_bundle.lua",
                "--preload-file @root@/Assets/Shader/Love/varying.def.sc@/game/Shader/Love/varying.def.sc",
                "--shell-file @web@/love-pthread-player-shell.html",
            }},
            {name = "dora-web-love-complex-probe", source = "Projects/Web/LoveComplexProbe.cpp", output = "dora-love-complex-probe", flags = {
                "--ignore-dynamic-linking",
                "-fwasm-exceptions",
                "-sSUPPORT_LONGJMP=wasm",
                "-sUSE_SDL=2",
                "-sUSE_WEBGL2=1",
                "-sFULL_ES3=1",
                "-sALLOW_MEMORY_GROWTH=1",
                "-sSTACK_SIZE=8MB",
                "-sINITIAL_MEMORY=64MB",
                "-sMAXIMUM_MEMORY=1GB",
                "-sEXIT_RUNTIME=0",
                "-sFILESYSTEM=1",
                "-sFETCH=1",
                "-lidbfs.js",
                "-sEXPORTED_FUNCTIONS=['_main','_dora_web_stop','_dora_web_set_suspended','_dora_web_release_input','_dora_web_love_complex_probe_start','_dora_web_love_complex_probe_status','_dora_web_love_complex_probe_release','_dora_web_love_complex_probe_frame','_dora_web_love_complex_probe_has_graphics','_dora_web_love_complex_probe_is_updating','_dora_web_love_complex_probe_runtime_status','_dora_web_love_complex_probe_audio_sources','_dora_web_love_complex_probe_audio_file_delta','_dora_web_love_complex_probe_voice_delta','_dora_web_love_complex_probe_pointer_presses','_dora_web_love_complex_probe_pointer_button','_dora_web_love_complex_probe_pointer_from_mouse','_dora_web_love_complex_probe_pointer_x','_dora_web_love_complex_probe_pointer_y','_dora_web_love_complex_probe_game_state','_dora_web_love_complex_probe_skip_tutorial','_dora_web_love_complex_probe_force_save','_dora_web_love_complex_probe_error']",
                "-sEXPORTED_RUNTIME_METHODS=['ccall','cwrap','UTF8ToString']",
                "--pre-js @web@/web-platform.js",
                "--pre-js @web@/love-complex-probe-runner.js",
                "--pre-js @web@/web-loader.js",
                "--preload-file @root@/Assets/Script/Lib/lualib_bundle.lua@/game/Script/Lib/lualib_bundle.lua",
                "--preload-file @root@/Assets/Shader/Love/varying.def.sc@/game/Shader/Love/varying.def.sc",
                "--preload-file @out@/love-complex-stage@/love-complex",
                "--shell-file @web@/player-shell.html",
            }},
        }
    }
end
