vec3 a_position : POSITION;
vec3 a_normal : NORMAL;
vec3 a_bitangent : BITANGENT;
vec3 a_tangent : TANGENT;
vec2 a_texcoord0 : TEXCOORD0;
vec4 a_color0 : COLOR0;
vec4 v_Color : TEXCOORD0;
vec2 v_UV : TEXCOORD1;
vec4 v_PosP : TEXCOORD2;