-- [ts]: UIX.ts
local ____exports = {} -- 1
local ____types = require("UIX.types") -- 1
local defaultInteractionState = ____types.defaultInteractionState -- 1
local mergeInteractionState = ____types.mergeInteractionState -- 1
local clamp = ____types.clamp -- 1
local ____theme = require("UIX.theme") -- 2
local doraPrismTheme = ____theme.doraPrismTheme -- 2
local mergeTheme = ____theme.mergeTheme -- 2
local ____context = require("UIX.context") -- 3
local getUiContext = ____context.getUiContext -- 3
local UiProvider = ____context.UiProvider -- 3
local ThemeScope = ____context.ThemeScope -- 3
local ____FocusManager = require("UIX.input.FocusManager") -- 4
local FocusManager = ____FocusManager.FocusManager -- 4
local ____Interaction = require("UIX.input.Interaction") -- 5
local useInteraction = ____Interaction.useInteraction -- 5
local ____PaintNode = require("UIX.paint.PaintNode") -- 6
local PaintNode = ____PaintNode.PaintNode -- 6
local ____color = require("UIX.paint.color") -- 7
local withAlpha = ____color.withAlpha -- 7
local mixColor = ____color.mixColor -- 7
local ____clip = require("UIX.paint.clip") -- 8
local registerClip = ____clip.registerClip -- 8
local unregisterClip = ____clip.unregisterClip -- 8
local applyAncestorClips = ____clip.applyAncestorClips -- 8
local ____primitives = require("UIX.paint.primitives") -- 9
local rect = ____primitives.rect -- 9
local roundedPanel = ____primitives.roundedPanel -- 9
local buttonSurface = ____primitives.buttonSurface -- 9
local progressTrack = ____primitives.progressTrack -- 9
local progressFill = ____primitives.progressFill -- 9
local focusRing = ____primitives.focusRing -- 9
local cooldownMask = ____primitives.cooldownMask -- 9
local itemSlotSurface = ____primitives.itemSlotSurface -- 9
local ____icons = require("UIX.paint.icons") -- 10
local iconPainters = ____icons.iconPainters -- 10
local drawIcon = ____icons.drawIcon -- 10
local ____Box = require("UIX.layout.Box") -- 11
local Box = ____Box.Box -- 11
local ____Row = require("UIX.layout.Row") -- 12
local Row = ____Row.Row -- 12
local ____Column = require("UIX.layout.Column") -- 13
local Column = ____Column.Column -- 13
local ____Stack = require("UIX.layout.Stack") -- 14
local Stack = ____Stack.Stack -- 14
local ____Spacer = require("UIX.layout.Spacer") -- 15
local Spacer = ____Spacer.Spacer -- 15
local ____Panel = require("UIX.layout.Panel") -- 16
local Panel = ____Panel.Panel -- 16
local ____ScrollView = require("UIX.layout.ScrollView") -- 17
local ScrollView = ____ScrollView.ScrollView -- 17
local ____Text = require("UIX.foundation.Text") -- 18
local Text = ____Text.Text -- 18
local wrapTextLines = ____Text.wrapTextLines -- 18
local ____Icon = require("UIX.foundation.Icon") -- 19
local Icon = ____Icon.Icon -- 19
local ____FocusRing = require("UIX.foundation.FocusRing") -- 20
local FocusRing = ____FocusRing.FocusRing -- 20
local ____Button = require("UIX.controls.Button") -- 21
local Button = ____Button.Button -- 21
local ____IconButton = require("UIX.controls.IconButton") -- 22
local IconButton = ____IconButton.IconButton -- 22
local ____ProgressBar = require("UIX.controls.ProgressBar") -- 23
local ProgressBar = ____ProgressBar.ProgressBar -- 23
local ____Slider = require("UIX.controls.Slider") -- 24
local Slider = ____Slider.Slider -- 24
local ____Tabs = require("UIX.controls.Tabs") -- 25
local Tabs = ____Tabs.Tabs -- 25
local ____Toggle = require("UIX.controls.Toggle") -- 26
local Toggle = ____Toggle.Toggle -- 26
local ____Tooltip = require("UIX.overlay.Tooltip") -- 27
local Tooltip = ____Tooltip.Tooltip -- 27
local ____Modal = require("UIX.overlay.Modal") -- 28
local Modal = ____Modal.Modal -- 28
local ____ToastStack = require("UIX.overlay.ToastStack") -- 29
local ToastStack = ____ToastStack.ToastStack -- 29
local ____HealthBar = require("UIX.game.HealthBar") -- 30
local HealthBar = ____HealthBar.HealthBar -- 30
local ____ResourceCounter = require("UIX.game.ResourceCounter") -- 31
local ResourceCounter = ____ResourceCounter.ResourceCounter -- 31
local ____CooldownButton = require("UIX.game.CooldownButton") -- 32
local CooldownButton = ____CooldownButton.CooldownButton -- 32
local ____ItemSlot = require("UIX.game.ItemSlot") -- 33
local ItemSlot = ____ItemSlot.ItemSlot -- 33
local ____InventoryGrid = require("UIX.game.InventoryGrid") -- 34
local InventoryGrid = ____InventoryGrid.InventoryGrid -- 34
____exports.defaultInteractionState = defaultInteractionState -- 37
____exports.mergeInteractionState = mergeInteractionState -- 38
____exports.clamp = clamp -- 39
____exports.doraPrismTheme = doraPrismTheme -- 40
____exports.mergeTheme = mergeTheme -- 41
____exports.getUiContext = getUiContext -- 42
____exports.UiProvider = UiProvider -- 43
____exports.ThemeScope = ThemeScope -- 44
____exports.FocusManager = FocusManager -- 45
____exports.useInteraction = useInteraction -- 46
____exports.PaintNode = PaintNode -- 47
____exports.withAlpha = withAlpha -- 48
____exports.mixColor = mixColor -- 49
____exports.registerClip = registerClip -- 50
____exports.unregisterClip = unregisterClip -- 51
____exports.applyAncestorClips = applyAncestorClips -- 52
____exports.rect = rect -- 53
____exports.roundedPanel = roundedPanel -- 54
____exports.buttonSurface = buttonSurface -- 55
____exports.progressTrack = progressTrack -- 56
____exports.progressFill = progressFill -- 57
____exports.focusRing = focusRing -- 58
____exports.cooldownMask = cooldownMask -- 59
____exports.itemSlotSurface = itemSlotSurface -- 60
____exports.iconPainters = iconPainters -- 61
____exports.drawIcon = drawIcon -- 62
____exports.Box = Box -- 63
____exports.Row = Row -- 64
____exports.Column = Column -- 65
____exports.Stack = Stack -- 66
____exports.Spacer = Spacer -- 67
____exports.Panel = Panel -- 68
____exports.ScrollView = ScrollView -- 69
____exports.Text = Text -- 70
____exports.wrapTextLines = wrapTextLines -- 71
____exports.Icon = Icon -- 72
____exports.FocusRing = FocusRing -- 73
____exports.Button = Button -- 74
____exports.IconButton = IconButton -- 75
____exports.ProgressBar = ProgressBar -- 76
____exports.Slider = Slider -- 77
____exports.Tabs = Tabs -- 78
____exports.Toggle = Toggle -- 79
____exports.Tooltip = Tooltip -- 80
____exports.Modal = Modal -- 81
____exports.ToastStack = ToastStack -- 82
____exports.HealthBar = HealthBar -- 83
____exports.ResourceCounter = ResourceCounter -- 84
____exports.CooldownButton = CooldownButton -- 85
____exports.ItemSlot = ItemSlot -- 86
____exports.InventoryGrid = InventoryGrid -- 87
return ____exports -- 87