_ENV = Dora
-- @preview-file on clear
local root = Node()
local sprite = Sprite('Image/logo.png')
sprite.size = Size(Vec2(200, 200))
root:onTapBegan(function(touch)
  sprite:perform(Move(1, sprite.position, touch.location, Ease.OutBack), false)
end)
local temp = Node()
temp:onUpdate(function()
  nvg.ApplyTransform(temp)
  nvg.BeginPath()
  nvg.RoundedRect((-150), 0, 300, 300, 20)
  nvg.FillColor(Color(Color3(0x3c6ffa), math.floor(0.8 * 255 + 0.5)))
  nvg.Fill()
end)
temp:gslot('MyEvent', function(arg0, arg1)
  p(({arg0, arg1}))
end)
threadLoop(function()
  sleep(1)
  p('abc')
end)
Audio:play('Audio/hero_win.wav', false)
Audio:playStream('Audio/Dismantlism Space.ogg', false, 0)
emit('MyEvent', 998, 'Hello')
temp.position = Vec2(0, 0)
local world = PhysicsWorld()
world.showDebug = true
local temp = (function()
  local bodyDef = BodyDef()
  bodyDef.type = 'Dynamic'
  bodyDef.group = 0
  bodyDef.linearAcceleration = Vec2(0, (-9.8))
  bodyDef:attachPolygon(Vec2(0, 150), 80, 80, 0, 1, 0.4, 0)
  return Body(bodyDef, world, Vec2(0, 0), 0)
end)()
local temp = (function()
  local bodyDef = BodyDef()
  bodyDef.type = 'Static'
  bodyDef.group = 0
  bodyDef.linearAcceleration = Vec2(0, (-9.8))
  bodyDef:attachPolygon(({Vec2((-100), (-50)), Vec2((-80), 0), Vec2(80, 0), Vec2(100, (-50))}), 1, 0.4, 0.4)
  return Body(bodyDef, world, Vec2(0, (-200)), 0)
end)()
return 123
