option("dora_love")
    set_default(true)
    set_showmenu(true)
    set_description("Build the Love compatibility layer")
option_end()

option("dora_ios_sign_identity")
    set_default("-")
    set_showmenu(true)
    set_description("iOS signing identity; '-' selects local ad-hoc signing")
option_end()
option("dora_ios_provision")
    set_showmenu(true)
    set_description("Installed iOS provisioning profile name for device signing")
option_end()

option("dora_yue")
    set_default(true)
    set_showmenu(true)
    set_description("Build YueScript support")
option_end()

option("dora_builtin_libs")
    set_default(true)
    set_showmenu(true)
    set_description("Embed built-in script libraries")
option_end()

option("dora_model_3d")
    set_default(true)
    set_showmenu(true)
    set_description("Build 3D model support")
option_end()

option("dora_music")
    set_default(true)
    set_showmenu(true)
    set_description("Build music support")
option_end()

option("dora_web_pthreads")
    set_default(false)
    set_showmenu(true)
    set_description("Enable the pthread Web profile")
option_end()
