/* Copyright (c) 2017-2026 Li Jin <dragon-fly@qq.com>

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */

import { DoraScene, DoraSceneNode } from './sceneTypes';

export type SceneCodeLanguage = "lua" | "typescript";

const quoteTypeScript = (value: string) => JSON.stringify(value);

const quoteLua = (value: string) => `"${value
	.replace(/\\/g, "\\\\")
	.replace(/"/g, "\\\"")
	.replace(/\n/g, "\\n")
	.replace(/\r/g, "\\r")
	.replace(/\t/g, "\\t")}"`;

const toIdentifier = (name: string, fallback: string) => {
	const normalized = name
		.replace(/[^a-zA-Z0-9_]/g, "_")
		.replace(/^[^a-zA-Z_]+/, "");
	return normalized.length > 0 ? normalized : fallback;
};

const uniqueNodeIdentifiers = (nodes: DoraSceneNode[]) => {
	const used = new Map<string, number>();
	const names = new Map<string, string>();
	for (const node of nodes) {
		const base = toIdentifier(node.name || node.id, "node");
		const nextIndex = used.get(base) ?? 0;
		used.set(base, nextIndex + 1);
		names.set(node.id, nextIndex === 0 ? base : `${base}${nextIndex + 1}`);
	}
	return names;
};

const sortedNodes = (scene: DoraScene) => {
	const result: DoraSceneNode[] = [];
	const visited = new Set<string>();
	const visit = (node: DoraSceneNode) => {
		if (visited.has(node.id)) return;
		if (node.parentId !== null) {
			const parent = scene.nodes.find(item => item.id === node.parentId);
			if (parent !== undefined) visit(parent);
		}
		visited.add(node.id);
		result.push(node);
	};
	for (const node of scene.nodes) {
		visit(node);
	}
	return result;
};

const nodeComment = (node: DoraSceneNode) => `${node.type}: ${node.name} (${node.id})`;

const normalizeScriptPath = (scriptPath: string) => scriptPath.trim().replace(/\\/g, "/").replace(/^\/+/, "");

const isTypeScriptScript = (scriptPath: string) => /\.(ts|tsx)$/i.test(scriptPath);

const isLuaRuntimeScript = (scriptPath: string) => /\.(lua|ts|tsx)$/i.test(scriptPath);

const toTypeScriptImportPath = (scriptPath: string) => {
	const normalized = normalizeScriptPath(scriptPath).replace(/\.(ts|tsx)$/i, "");
	return normalized.startsWith(".") ? normalized : `./${normalized}`;
};

const toLuaRequirePath = (scriptPath: string) => normalizeScriptPath(scriptPath)
	.replace(/\.(lua|ts|tsx)$/i, "")
	.replace(/^\.\//, "")
	.replace(/\//g, ".");

export const generateSceneTypeScript = (scene: DoraScene) => {
	const identifiers = uniqueNodeIdentifiers(scene.nodes);
	const orderedNodes = sortedNodes(scene);
	const scriptAttachNames = new Map<string, string>();
	const scriptImports: string[] = [];
	let scriptIndex = 0;
	for (const node of orderedNodes) {
		const scriptPath = node.script?.trim() ?? "";
		if (scriptPath.length === 0 || !isTypeScriptScript(scriptPath)) continue;
		const attachName = `attachSceneScript${scriptIndex}`;
		scriptAttachNames.set(node.id, attachName);
		scriptImports.push(`import { attach as ${attachName} } from ${quoteTypeScript(toTypeScriptImportPath(scriptPath))};`);
		scriptIndex++;
	}
	const lines: string[] = [
		"// Generated by Dora Scene Editor. Edit the .scene.json file, then regenerate.",
		"import { App, Director, Label, Node, Size, Sprite } from 'Dora';",
		...scriptImports,
		"",
		"function applyTransform(node: Node.Type, x: number, y: number, scaleX: number, scaleY: number, angle: number, visible: boolean, tag: string) {",
		"\tnode.x = x;",
		"\tnode.y = y;",
		"\tnode.scaleX = scaleX;",
		"\tnode.scaleY = scaleY;",
		"\tnode.angle = angle;",
		"\tnode.visible = visible;",
		"\tnode.tag = tag;",
		"}",
		"",
		"export function createScene() {",
		"\tconst sceneNodes: Record<string, Node.Type> = {};",
	];

	for (const node of orderedNodes) {
		const variableName = identifiers.get(node.id) ?? "node";
		lines.push("", `\t// ${nodeComment(node)}`, "\t{");
		switch (node.type) {
			case "Sprite": {
				const texture = node.texture?.trim() ?? "";
				if (texture.length > 0) {
					lines.push(`\t\tconst ${variableName} = Sprite(${quoteTypeScript(texture)}) ?? Sprite();`);
				} else {
					lines.push(`\t\tconst ${variableName} = Sprite();`);
				}
				break;
			}
			case "Label": {
				const fontSize = node.fontSize ?? 32;
				lines.push(`\t\tconst labelNode = Label("sarasa-mono-sc-regular", ${fontSize});`);
				lines.push(`\t\tconst ${variableName} = labelNode ?? Node();`);
				lines.push(`\t\tif (labelNode !== undefined) labelNode.text = ${quoteTypeScript(node.text ?? node.name)};`);
				break;
			}
			default:
				lines.push(`\t\tconst ${variableName} = Node();`);
				break;
		}
		lines.push(`\t\tapplyTransform(${variableName}, ${node.x}, ${node.y}, ${node.scaleX}, ${node.scaleY}, ${node.rotation}, ${node.visible}, ${quoteTypeScript(node.name)});`);
		lines.push(`\t\tsceneNodes[${quoteTypeScript(node.id)}] = ${variableName};`);
		if (node.parentId !== null) {
			lines.push(`\t\tconst parent = sceneNodes[${quoteTypeScript(node.parentId)}];`);
			lines.push(`\t\tif (parent !== undefined) parent.addChild(${variableName});`);
		}
		const attachName = scriptAttachNames.get(node.id);
		if (attachName !== undefined) {
			lines.push(`\t\t${attachName}(${variableName}, sceneNodes);`);
		}
		lines.push("\t}");
	}

	lines.push(
		"",
		`\treturn sceneNodes[${quoteTypeScript(scene.rootId)}];`,
		"}",
		"",
		`App.winSize = Size(${scene.viewport.width}, ${scene.viewport.height});`,
		"",
		"Director.entry.addChild(createScene());",
		""
	);
	return lines.join("\n");
};

export const generateSceneLua = (scene: DoraScene) => {
	const identifiers = uniqueNodeIdentifiers(scene.nodes);
	const orderedNodes = sortedNodes(scene);
	const scriptNodes = orderedNodes.filter(node => {
		const scriptPath = node.script?.trim() ?? "";
		return scriptPath.length > 0 && isLuaRuntimeScript(scriptPath);
	});
	const lines: string[] = [
		"-- Generated by Dora Scene Editor. Edit the .scene.json file, then regenerate.",
		"local ____Dora = require(\"Dora\")",
		"local App = ____Dora.App",
		"local Director = ____Dora.Director",
		"local Label = ____Dora.Label",
		"local Node = ____Dora.Node",
		"local Size = ____Dora.Size",
		"local Sprite = ____Dora.Sprite",
		"",
		"local function applyTransform(node, x, y, scaleX, scaleY, angle, visible, tag)",
		"\tnode.x = x",
		"\tnode.y = y",
		"\tnode.scaleX = scaleX",
		"\tnode.scaleY = scaleY",
		"\tnode.angle = angle",
		"\tnode.visible = visible",
		"\tnode.tag = tag",
		"end",
		"",
		"local scriptModules = {}",
		...scriptNodes.flatMap(node => [
			"do",
			`\tlocal ok, scriptModule = pcall(require, ${quoteLua(toLuaRequirePath(node.script ?? ""))})`,
			`\tif ok and scriptModule then scriptModules[${quoteLua(node.id)}] = scriptModule end`,
			"end",
		]),
		scriptNodes.length > 0 ? "" : "",
		"local function createScene()",
		"\tlocal sceneNodes = {}",
	];

	for (const node of orderedNodes) {
		const variableName = identifiers.get(node.id) ?? "node";
		lines.push("", `\t-- ${nodeComment(node)}`, "\tdo");
		switch (node.type) {
			case "Sprite": {
				const texture = node.texture?.trim() ?? "";
				if (texture.length > 0) {
					lines.push(`\t\tlocal ${variableName} = Sprite(${quoteLua(texture)}) or Sprite()`);
				} else {
					lines.push(`\t\tlocal ${variableName} = Sprite()`);
				}
				break;
			}
			case "Label": {
				const fontSize = node.fontSize ?? 32;
				lines.push(`\t\tlocal labelNode = Label("sarasa-mono-sc-regular", ${fontSize})`);
				lines.push(`\t\tlocal ${variableName} = labelNode or Node()`);
				lines.push(`\t\tif labelNode then labelNode.text = ${quoteLua(node.text ?? node.name)} end`);
				break;
			}
			default:
				lines.push(`\t\tlocal ${variableName} = Node()`);
				break;
		}
		lines.push(`\t\tapplyTransform(${variableName}, ${node.x}, ${node.y}, ${node.scaleX}, ${node.scaleY}, ${node.rotation}, ${node.visible}, ${quoteLua(node.name)})`);
		lines.push(`\t\tsceneNodes[${quoteLua(node.id)}] = ${variableName}`);
		if (node.parentId !== null) {
			lines.push(`\t\tlocal parent = sceneNodes[${quoteLua(node.parentId)}]`);
			lines.push(`\t\tif parent then parent:addChild(${variableName}) end`);
		}
		if (scriptNodes.some(scriptNode => scriptNode.id === node.id)) {
			lines.push(`\t\tlocal scriptModule = scriptModules[${quoteLua(node.id)}]`);
			lines.push(`\t\tif scriptModule and scriptModule.attach then scriptModule.attach(${variableName}, sceneNodes) end`);
		}
		lines.push("\tend");
	}

	lines.push(
		"",
		`\treturn sceneNodes[${quoteLua(scene.rootId)}]`,
		"end",
		"",
		`App.winSize = Size(${scene.viewport.width}, ${scene.viewport.height})`,
		"",
		"Director.entry:addChild(createScene())",
		"",
		"return {",
		"\tcreateScene = createScene",
		"}",
		""
	);
	return lines.join("\n");
};
