local Color = require("Color").Type

-- Creates a new `Color` object using the RGBA color channel values.
-- @param r (number) The red channel value (0-255).
-- @param g (number) The green channel value (0-255).
-- @param b (number) The blue channel value (0-255).
-- @param a (number) The alpha channel value (0-1).
-- @return (Color) The new `Color` object.
local rgba: function(r: number, g: number, b: number, a: number): Color

return rgba
