#!/usr/bin/env python3
"""Align original RGBA poses by crop and integer translation; no pixel editing."""
import argparse
from collections import deque
import hashlib
import json
from pathlib import Path
from statistics import median

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[3]
SOURCE = Path(__file__).with_name('dora-remix-states.original.png')
DEST = ROOT / 'Assets/Image/Mobile/dora-remix-states.png'
LAYOUT = ROOT / 'Assets/Script/Dev/Mobile/MascotFrames.ts'
CELL = 272
PIVOT = (136, 248)
PADDING = 4
STATES = ('idle', 'waiting', 'thinking', 'working', 'success', 'failed')


def components(image):
    """Segment the whole sheet, not assumed 256px cells (which cut poses)."""
    width, height = image.size
    mask = bytearray(a >= 128 for r, g, b, a in image.get_flattened_data())
    found = []
    for index in range(len(mask)):
        if not mask[index]:
            continue
        queue = deque([index])
        mask[index] = 0
        points = []
        while queue:
            p = queue.popleft()
            y, x = divmod(p, width)
            points.append((x, y))
            for nx, ny in ((x-1, y), (x+1, y), (x, y-1), (x, y+1)):
                if 0 <= nx < width and 0 <= ny < height:
                    n = ny * width + nx
                    if mask[n]:
                        mask[n] = 0
                        queue.append(n)
        if len(points) > 1000:
            xs, ys = zip(*points)
            found.append((min(xs), min(ys), max(xs)+1, max(ys)+1))
    if len(found) != 24:
        raise ValueError(f'Expected 24 separate characters, found {len(found)}')
    found.sort(key=lambda b: (b[1]+b[3])/2)
    return [box for row in range(6) for box in sorted(found[row*4:row*4+4])]


def feet(image, box):
    """Use the lower shoe band, not head/bounding-box center (tilted poses)."""
    pixels = image.load()
    left, top, right, bottom = box
    rows = []
    for y in range(bottom-16, bottom):
        xs = [x for x in range(left, right) if pixels[x, y][3] >= 192]
        if len(xs) >= 6:
            rows.append((y, (min(xs)+max(xs)+1)/2))
    if not rows:
        raise ValueError(f'No feet in {box}')
    return median(x for y, x in rows), max(y for y, x in rows)+1


def align(image):
    frames, metadata = [], []
    for i, box in enumerate(components(image)):
        pivot = feet(image, box)
        crop = (max(0,box[0]-PADDING), max(0,box[1]-PADDING),
                min(image.width,box[2]+PADDING), min(image.height,box[3]+PADDING))
        shift = (round(PIVOT[0]-pivot[0]), round(PIVOT[1]-pivot[1]))
        dest = (crop[0]+shift[0], crop[1]+shift[1])
        assert dest[0] >= 1 and dest[1] >= 1
        assert dest[0]+crop[2]-crop[0] < CELL and dest[1]+crop[3]-crop[1] < CELL
        frame = Image.new('RGBA',(CELL,CELL))
        # No mask: masked paste would multiply alpha and change original RGBA.
        frame.paste(image.crop(crop), dest)
        frames.append(frame)
        metadata.append(dict(state=STATES[i//4], frame=i%4, source_box=box,
                             source_crop=crop, source_pivot=pivot, destination=dest,
                             translation=shift, pivot=[pivot[j]+shift[j] for j in (0,1)]))
    return frames, metadata


def layout_source(metadata):
    pivots = ', '.join(str(f['pivot'][0]) for f in metadata)
    return ('// Generated by Tools/Art/Mobile/rebuild_mascot.py. Do not hand-edit.\n'
            f'export const MASCOT_CELL_SIZE = {CELL};\n'
            f'export const MASCOT_PIVOT_Y = {PIVOT[1]};\n'
            f'export const MASCOT_FRAME_PIVOT_X: number[] = [{pivots}];\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=DEST)
    parser.add_argument('--layout-output', type=Path)
    parser.add_argument('--evidence', type=Path, required=True)
    args = parser.parse_args()
    source = Image.open(SOURCE).convert('RGBA')
    frames, metadata = align(source)
    atlas = Image.new('RGBA', (CELL*4, CELL*6))
    for i, f in enumerate(frames):
        atlas.paste(f, ((i%4)*CELL, (i//4)*CELL))
    output = atlas
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.evidence.mkdir(parents=True, exist_ok=True)
    output.save(args.output)
    layout_output = args.layout_output or (LAYOUT if args.output.resolve()==DEST.resolve() else args.evidence/'MascotFrames.ts')
    layout_output.parent.mkdir(parents=True,exist_ok=True)
    layout_output.write_text(layout_source(metadata))
    report = dict(mode='original-rgba-alignment-only',source_sha256=hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
                  atlas_sha256=hashlib.sha256(args.output.read_bytes()).hexdigest(),cell_size=CELL,
                  target_pivot=PIVOT,padding=PADDING,frames=metadata)
    (args.evidence/'atlas.json').write_text(json.dumps(report, indent=2)+'\n')
    # Contact sheet is derived solely from the translated source frames.
    preview = Image.new('RGB', output.size, '#242b38')
    preview.paste(output, mask=output.getchannel('A'))
    draw = ImageDraw.Draw(preview)
    for row in range(6):
        y=row*CELL+PIVOT[1]
        draw.line((0,y,preview.width,y),fill='#628472')
    preview.save(args.evidence/'contact-sheet.png')
    print(f'Wrote original-RGBA atlas {atlas.size}: {args.output}')
    print('24 source rectangles copied unchanged; fractional pivots recorded for runtime alignment.')


if __name__ == '__main__':
    main()
