import { ParticleFields, createFireParticleFields } from "./ParticleDocument";

export type ParticlePresetId = "fire" | "explosion" | "rain" | "smoke" | "spark" | "snow" | "magic" | "fireworks" | "dust" | "waterfall" | "trail" | "heal" | "portal" | "hitImpact" | "slash" | "muzzleFlash" | "blood" | "poison" | "electric" | "pickup" | "shield";

export type ParticlePreset = {
	id: ParticlePresetId;
	label: string;
	fields: () => ParticleFields;
};

const vec4 = (x: number, y: number, z: number, w: number) => ({ x, y, z, w });
const vec2 = (x: number, y: number) => ({ x, y });

export const particlePresets: readonly ParticlePreset[] = [
	{
		id: "fire",
		label: "Fire",
		fields: createFireParticleFields,
	},
	{
		id: "explosion",
		label: "Explosion",
		fields: () => ({
			...createFireParticleFields(),
			duration: 0.18,
			emissionRate: 2200,
			maxParticles: 420,
			particleLifespan: 0.62,
			particleLifespanVariance: 0.22,
			angle: 90,
			angleVariance: 360,
			startColor: vec4(1, 0.76, 0.22, 1),
			startColorVariance: vec4(0.08, 0.12, 0.05, 0),
			finishColor: vec4(0.42, 0.06, 0.01, 0),
			finishColorVariance: vec4(0.12, 0.04, 0.01, 0),
			startParticleSize: 46,
			startParticleSizeVariance: 24,
			finishParticleSize: 8,
			finishParticleSizeVariance: 10,
			gravity: {
				rotationIsDir: false,
				gravity: vec2(0, -85),
				speed: 260,
				speedVariance: 95,
				radialAcceleration: -110,
				radialAccelVariance: 45,
				tangentialAcceleration: 0,
				tangentialAccelVariance: 0,
			},
		}),
	},
	{
		id: "rain",
		label: "Rain",
		fields: () => ({
			...createFireParticleFields(),
			duration: -1,
			emissionRate: 460,
			maxParticles: 900,
			particleLifespan: 1.25,
			particleLifespanVariance: 0.28,
			angle: 265,
			angleVariance: 8,
			startPositionVariance: vec2(360, 20),
			startColor: vec4(0.48, 0.68, 1, 0.72),
			startColorVariance: vec4(0.06, 0.08, 0.08, 0.12),
			finishColor: vec4(0.34, 0.52, 0.95, 0.2),
			finishColorVariance: vec4(0.04, 0.06, 0.05, 0.08),
			startParticleSize: 7,
			startParticleSizeVariance: 2,
			finishParticleSize: 3,
			finishParticleSizeVariance: 1,
			gravity: {
				rotationIsDir: true,
				gravity: vec2(0, -720),
				speed: 420,
				speedVariance: 45,
				radialAcceleration: 0,
				radialAccelVariance: 0,
				tangentialAcceleration: 0,
				tangentialAccelVariance: 0,
			},
		}),
	},
	{
		id: "smoke",
		label: "Smoke",
		fields: () => ({
			...createFireParticleFields(),
			duration: -1,
			emissionRate: 90,
			maxParticles: 240,
			particleLifespan: 2.8,
			particleLifespanVariance: 0.8,
			angle: 95,
			angleVariance: 24,
			startPositionVariance: vec2(12, 4),
			startColor: vec4(0.26, 0.26, 0.26, 0.42),
			startColorVariance: vec4(0.08, 0.08, 0.08, 0.12),
			finishColor: vec4(0.08, 0.08, 0.08, 0),
			finishColorVariance: vec4(0.04, 0.04, 0.04, 0),
			startParticleSize: 28,
			startParticleSizeVariance: 12,
			finishParticleSize: 84,
			finishParticleSizeVariance: 26,
			gravity: {
				rotationIsDir: false,
				gravity: vec2(0, 18),
				speed: 34,
				speedVariance: 18,
				radialAcceleration: 0,
				radialAccelVariance: 0,
				tangentialAcceleration: 12,
				tangentialAccelVariance: 16,
			},
		}),
	},
		{
			id: "spark",
		label: "Spark",
		fields: () => ({
			...createFireParticleFields(),
			duration: 0.12,
			emissionRate: 1200,
			maxParticles: 260,
			particleLifespan: 0.52,
			particleLifespanVariance: 0.26,
			angle: 90,
			angleVariance: 360,
			startColor: vec4(1, 0.95, 0.55, 1),
			startColorVariance: vec4(0.05, 0.04, 0.08, 0),
			finishColor: vec4(1, 0.22, 0.04, 0),
			finishColorVariance: vec4(0.08, 0.08, 0.02, 0),
			startParticleSize: 10,
			startParticleSizeVariance: 5,
			finishParticleSize: 1,
			finishParticleSizeVariance: 1,
			gravity: {
				rotationIsDir: true,
				gravity: vec2(0, -260),
				speed: 360,
				speedVariance: 120,
				radialAcceleration: 0,
				radialAccelVariance: 0,
				tangentialAcceleration: 0,
				tangentialAccelVariance: 0,
			},
			}),
		},
		{
			id: "snow",
			label: "Snow",
			fields: () => ({
				...createFireParticleFields(),
				duration: -1,
				emissionRate: 120,
				maxParticles: 520,
				particleLifespan: 5.8,
				particleLifespanVariance: 1.8,
				angle: 268,
				angleVariance: 18,
				startPositionVariance: vec2(360, 24),
				startColor: vec4(0.92, 0.97, 1, 0.9),
				startColorVariance: vec4(0.04, 0.03, 0.02, 0.14),
				finishColor: vec4(0.82, 0.9, 1, 0.12),
				finishColorVariance: vec4(0.04, 0.04, 0.02, 0.08),
				startParticleSize: 9,
				startParticleSizeVariance: 5,
				finishParticleSize: 7,
				finishParticleSizeVariance: 4,
				gravity: {
					rotationIsDir: false,
					gravity: vec2(18, -22),
					speed: 46,
					speedVariance: 24,
					radialAcceleration: 0,
					radialAccelVariance: 0,
					tangentialAcceleration: 8,
					tangentialAccelVariance: 18,
				},
			}),
		},
		{
			id: "magic",
			label: "Magic",
			fields: () => ({
				...createFireParticleFields(),
				duration: -1,
				emissionRate: 160,
				maxParticles: 420,
				particleLifespan: 1.8,
				particleLifespanVariance: 0.55,
				angle: 90,
				angleVariance: 360,
				startPositionVariance: vec2(22, 22),
				startColor: vec4(0.42, 0.88, 1, 0.9),
				startColorVariance: vec4(0.32, 0.18, 0.22, 0.08),
				finishColor: vec4(0.72, 0.18, 1, 0),
				finishColorVariance: vec4(0.2, 0.16, 0.12, 0),
				startParticleSize: 14,
				startParticleSizeVariance: 9,
				finishParticleSize: 2,
				finishParticleSizeVariance: 2,
				gravity: {
					rotationIsDir: false,
					gravity: vec2(0, 24),
					speed: 86,
					speedVariance: 42,
					radialAcceleration: -18,
					radialAccelVariance: 10,
					tangentialAcceleration: 38,
					tangentialAccelVariance: 50,
				},
			}),
		},
		{
			id: "fireworks",
			label: "Fireworks",
			fields: () => ({
				...createFireParticleFields(),
				duration: 0.08,
				emissionRate: 2600,
				maxParticles: 520,
				particleLifespan: 1.35,
				particleLifespanVariance: 0.35,
				angle: 90,
				angleVariance: 360,
				startColor: vec4(1, 0.9, 0.34, 1),
				startColorVariance: vec4(0.45, 0.42, 0.38, 0),
				finishColor: vec4(0.08, 0.14, 0.5, 0),
				finishColorVariance: vec4(0.2, 0.18, 0.36, 0),
				startParticleSize: 12,
				startParticleSizeVariance: 7,
				finishParticleSize: 1,
				finishParticleSizeVariance: 1,
				gravity: {
					rotationIsDir: true,
					gravity: vec2(0, -165),
					speed: 315,
					speedVariance: 85,
					radialAcceleration: -70,
					radialAccelVariance: 22,
					tangentialAcceleration: 0,
					tangentialAccelVariance: 0,
				},
			}),
		},
		{
			id: "dust",
			label: "Dust",
			fields: () => ({
				...createFireParticleFields(),
				duration: -1,
				emissionRate: 52,
				maxParticles: 180,
				particleLifespan: 3.4,
				particleLifespanVariance: 1.2,
				angle: 88,
				angleVariance: 48,
				startPositionVariance: vec2(34, 8),
				startColor: vec4(0.62, 0.52, 0.34, 0.24),
				startColorVariance: vec4(0.14, 0.12, 0.08, 0.08),
				finishColor: vec4(0.38, 0.32, 0.22, 0),
				finishColorVariance: vec4(0.08, 0.08, 0.05, 0),
				startParticleSize: 16,
				startParticleSizeVariance: 9,
				finishParticleSize: 42,
				finishParticleSizeVariance: 20,
				gravity: {
					rotationIsDir: false,
					gravity: vec2(8, 14),
					speed: 28,
					speedVariance: 18,
					radialAcceleration: 0,
					radialAccelVariance: 0,
					tangentialAcceleration: 10,
					tangentialAccelVariance: 18,
				},
			}),
		},
		{
			id: "waterfall",
			label: "Waterfall",
			fields: () => ({
				...createFireParticleFields(),
				duration: -1,
				emissionRate: 520,
				maxParticles: 760,
				particleLifespan: 1.45,
				particleLifespanVariance: 0.3,
				angle: 270,
				angleVariance: 10,
				startPositionVariance: vec2(42, 4),
				startColor: vec4(0.55, 0.82, 1, 0.82),
				startColorVariance: vec4(0.08, 0.08, 0.05, 0.12),
				finishColor: vec4(0.25, 0.58, 1, 0.12),
				finishColorVariance: vec4(0.04, 0.06, 0.04, 0.08),
				startParticleSize: 11,
				startParticleSizeVariance: 4,
				finishParticleSize: 5,
				finishParticleSizeVariance: 3,
				gravity: {
					rotationIsDir: true,
					gravity: vec2(0, -640),
					speed: 280,
					speedVariance: 55,
					radialAcceleration: 0,
					radialAccelVariance: 0,
					tangentialAcceleration: 0,
					tangentialAccelVariance: 0,
				},
			}),
		},
		{
			id: "trail",
			label: "Trail",
			fields: () => ({
				...createFireParticleFields(),
				duration: -1,
				emissionRate: 240,
				maxParticles: 180,
				particleLifespan: 0.55,
				particleLifespanVariance: 0.12,
				angle: 90,
				angleVariance: 360,
				startPositionVariance: vec2(5, 5),
				startColor: vec4(1, 0.78, 0.32, 0.82),
				startColorVariance: vec4(0.12, 0.08, 0.04, 0.08),
				finishColor: vec4(0.9, 0.18, 0.06, 0),
				finishColorVariance: vec4(0.08, 0.04, 0.02, 0),
				startParticleSize: 18,
				startParticleSizeVariance: 6,
				finishParticleSize: 1,
				finishParticleSizeVariance: 1,
				gravity: {
					rotationIsDir: false,
					gravity: vec2(0, 0),
					speed: 18,
					speedVariance: 10,
					radialAcceleration: 0,
					radialAccelVariance: 0,
					tangentialAcceleration: 0,
					tangentialAccelVariance: 0,
				},
			}),
		},
		{
			id: "heal",
			label: "Heal",
			fields: () => ({
				...createFireParticleFields(),
				duration: -1,
				emissionRate: 110,
				maxParticles: 260,
				particleLifespan: 1.9,
				particleLifespanVariance: 0.45,
				angle: 92,
				angleVariance: 28,
				startPositionVariance: vec2(28, 8),
				startColor: vec4(0.58, 1, 0.42, 0.78),
				startColorVariance: vec4(0.16, 0.12, 0.08, 0.1),
				finishColor: vec4(1, 0.86, 0.28, 0),
				finishColorVariance: vec4(0.12, 0.08, 0.04, 0),
				startParticleSize: 16,
				startParticleSizeVariance: 8,
				finishParticleSize: 4,
				finishParticleSizeVariance: 3,
				gravity: {
					rotationIsDir: false,
					gravity: vec2(0, 36),
					speed: 62,
					speedVariance: 22,
					radialAcceleration: -6,
					radialAccelVariance: 4,
					tangentialAcceleration: 18,
					tangentialAccelVariance: 24,
				},
			}),
		},
			{
				id: "portal",
			label: "Portal",
			fields: () => ({
				...createFireParticleFields(),
				duration: -1,
				emissionRate: 180,
				maxParticles: 360,
				particleLifespan: 1.6,
				particleLifespanVariance: 0.35,
				angle: 0,
				angleVariance: 360,
				startColor: vec4(0.18, 0.9, 1, 0.9),
				startColorVariance: vec4(0.12, 0.12, 0.2, 0.08),
				finishColor: vec4(0.72, 0.15, 1, 0),
				finishColorVariance: vec4(0.14, 0.08, 0.1, 0),
				startParticleSize: 18,
				startParticleSizeVariance: 8,
				finishParticleSize: 2,
				finishParticleSizeVariance: 2,
				emitterMode: "radius",
				radius: {
					startRadius: 120,
					startRadiusVariance: 22,
					finishRadius: 28,
					finishRadiusVariance: 10,
					rotatePerSecond: 210,
					rotatePerSecondVariance: 45,
					},
				}),
			},
			{
				id: "hitImpact",
				label: "Hit Impact",
				fields: () => ({
					...createFireParticleFields(),
					duration: 0.06,
					emissionRate: 1800,
					maxParticles: 180,
					particleLifespan: 0.28,
					particleLifespanVariance: 0.12,
					angle: 90,
					angleVariance: 360,
					startColor: vec4(1, 0.96, 0.78, 1),
					startColorVariance: vec4(0.08, 0.08, 0.12, 0),
					finishColor: vec4(1, 0.42, 0.08, 0),
					finishColorVariance: vec4(0.18, 0.1, 0.04, 0),
					startParticleSize: 22,
					startParticleSizeVariance: 14,
					finishParticleSize: 1,
					finishParticleSizeVariance: 1,
					gravity: {
						rotationIsDir: true,
						gravity: vec2(0, -80),
						speed: 240,
						speedVariance: 90,
						radialAcceleration: -120,
						radialAccelVariance: 40,
						tangentialAcceleration: 0,
						tangentialAccelVariance: 0,
					},
				}),
			},
			{
				id: "slash",
				label: "Slash",
				fields: () => ({
					...createFireParticleFields(),
					duration: 0.12,
					emissionRate: 1100,
					maxParticles: 220,
					particleLifespan: 0.42,
					particleLifespanVariance: 0.14,
					angle: 15,
					angleVariance: 26,
					startPositionVariance: vec2(44, 6),
					startColor: vec4(0.78, 0.9, 1, 0.92),
					startColorVariance: vec4(0.08, 0.08, 0.08, 0.08),
					finishColor: vec4(0.2, 0.56, 1, 0),
					finishColorVariance: vec4(0.08, 0.12, 0.12, 0),
					startParticleSize: 20,
					startParticleSizeVariance: 10,
					finishParticleSize: 2,
					finishParticleSizeVariance: 2,
					gravity: {
						rotationIsDir: true,
						gravity: vec2(0, 0),
						speed: 250,
						speedVariance: 50,
						radialAcceleration: -70,
						radialAccelVariance: 20,
						tangentialAcceleration: 0,
						tangentialAccelVariance: 0,
					},
				}),
			},
			{
				id: "muzzleFlash",
				label: "Muzzle",
				fields: () => ({
					...createFireParticleFields(),
					duration: 0.04,
					emissionRate: 2600,
					maxParticles: 130,
					particleLifespan: 0.16,
					particleLifespanVariance: 0.06,
					angle: 0,
					angleVariance: 24,
					startColor: vec4(1, 0.96, 0.72, 1),
					startColorVariance: vec4(0.04, 0.08, 0.12, 0),
					finishColor: vec4(1, 0.34, 0.04, 0),
					finishColorVariance: vec4(0.08, 0.08, 0.02, 0),
					startParticleSize: 36,
					startParticleSizeVariance: 16,
					finishParticleSize: 1,
					finishParticleSizeVariance: 1,
					gravity: {
						rotationIsDir: true,
						gravity: vec2(0, 0),
						speed: 360,
						speedVariance: 80,
						radialAcceleration: -260,
						radialAccelVariance: 60,
						tangentialAcceleration: 0,
						tangentialAccelVariance: 0,
					},
				}),
			},
			{
				id: "blood",
				label: "Blood",
				fields: () => ({
					...createFireParticleFields(),
					duration: 0.18,
					emissionRate: 850,
					maxParticles: 180,
					particleLifespan: 0.9,
					particleLifespanVariance: 0.28,
					angle: 110,
					angleVariance: 120,
					startColor: vec4(0.72, 0.02, 0.02, 0.94),
					startColorVariance: vec4(0.16, 0.02, 0.02, 0.06),
					finishColor: vec4(0.22, 0, 0, 0),
					finishColorVariance: vec4(0.08, 0, 0, 0),
					startParticleSize: 11,
					startParticleSizeVariance: 7,
					finishParticleSize: 4,
					finishParticleSizeVariance: 3,
					gravity: {
						rotationIsDir: true,
						gravity: vec2(0, -420),
						speed: 220,
						speedVariance: 120,
						radialAcceleration: 0,
						radialAccelVariance: 0,
						tangentialAcceleration: 0,
						tangentialAccelVariance: 0,
					},
				}),
			},
			{
				id: "poison",
				label: "Poison",
				fields: () => ({
					...createFireParticleFields(),
					duration: -1,
					emissionRate: 78,
					maxParticles: 240,
					particleLifespan: 2.6,
					particleLifespanVariance: 0.75,
					angle: 92,
					angleVariance: 40,
					startPositionVariance: vec2(26, 8),
					startColor: vec4(0.32, 0.92, 0.18, 0.38),
					startColorVariance: vec4(0.1, 0.16, 0.08, 0.1),
					finishColor: vec4(0.06, 0.32, 0.04, 0),
					finishColorVariance: vec4(0.04, 0.1, 0.04, 0),
					startParticleSize: 20,
					startParticleSizeVariance: 10,
					finishParticleSize: 68,
					finishParticleSizeVariance: 24,
					gravity: {
						rotationIsDir: false,
						gravity: vec2(0, 16),
						speed: 34,
						speedVariance: 18,
						radialAcceleration: 0,
						radialAccelVariance: 0,
						tangentialAcceleration: 20,
						tangentialAccelVariance: 28,
					},
				}),
			},
			{
				id: "electric",
				label: "Electric",
				fields: () => ({
					...createFireParticleFields(),
					duration: 0.16,
					emissionRate: 1500,
					maxParticles: 220,
					particleLifespan: 0.34,
					particleLifespanVariance: 0.16,
					angle: 90,
					angleVariance: 360,
					startColor: vec4(0.62, 0.9, 1, 1),
					startColorVariance: vec4(0.12, 0.08, 0.04, 0),
					finishColor: vec4(0.18, 0.28, 1, 0),
					finishColorVariance: vec4(0.08, 0.12, 0.18, 0),
					startParticleSize: 9,
					startParticleSizeVariance: 6,
					finishParticleSize: 1,
					finishParticleSizeVariance: 1,
					gravity: {
						rotationIsDir: true,
						gravity: vec2(0, 0),
						speed: 420,
						speedVariance: 160,
						radialAcceleration: -160,
						radialAccelVariance: 60,
						tangentialAcceleration: 90,
						tangentialAccelVariance: 120,
					},
				}),
			},
			{
				id: "pickup",
				label: "Pickup",
				fields: () => ({
					...createFireParticleFields(),
					duration: 0.42,
					emissionRate: 380,
					maxParticles: 160,
					particleLifespan: 0.9,
					particleLifespanVariance: 0.18,
					angle: 90,
					angleVariance: 50,
					startPositionVariance: vec2(20, 6),
					startColor: vec4(1, 0.88, 0.22, 0.95),
					startColorVariance: vec4(0.08, 0.08, 0.08, 0.05),
					finishColor: vec4(1, 1, 0.76, 0),
					finishColorVariance: vec4(0.04, 0.04, 0.08, 0),
					startParticleSize: 13,
					startParticleSizeVariance: 6,
					finishParticleSize: 2,
					finishParticleSizeVariance: 1,
					gravity: {
						rotationIsDir: false,
						gravity: vec2(0, 72),
						speed: 72,
						speedVariance: 26,
						radialAcceleration: -22,
						radialAccelVariance: 8,
						tangentialAcceleration: 28,
						tangentialAccelVariance: 36,
					},
				}),
			},
			{
				id: "shield",
				label: "Shield",
				fields: () => ({
					...createFireParticleFields(),
					duration: -1,
					emissionRate: 140,
					maxParticles: 300,
					particleLifespan: 1.25,
					particleLifespanVariance: 0.25,
					angle: 0,
					angleVariance: 360,
					startColor: vec4(0.28, 0.72, 1, 0.72),
					startColorVariance: vec4(0.08, 0.1, 0.08, 0.08),
					finishColor: vec4(0.06, 0.22, 0.9, 0),
					finishColorVariance: vec4(0.04, 0.06, 0.12, 0),
					startParticleSize: 16,
					startParticleSizeVariance: 6,
					finishParticleSize: 3,
					finishParticleSizeVariance: 2,
					emitterMode: "radius",
					radius: {
						startRadius: 78,
						startRadiusVariance: 6,
						finishRadius: 118,
						finishRadiusVariance: 10,
						rotatePerSecond: 160,
						rotatePerSecondVariance: 24,
					},
				}),
			},
		];

export const createParticlePresetFields = (id: ParticlePresetId) => {
	const preset = particlePresets.find((item) => item.id === id);
	return (preset ?? particlePresets[0]).fields();
};
