name: Emscripten

on:
  push:
    branches: [ main ]
    paths:
      - 'Source/**'
      - 'Projects/Emscripten/**'
      - 'Tools/build-scripts/build_emscripten.sh'
      - 'Tools/build-scripts/build_wa_web.sh'
      - 'Tools/build-scripts/check_emscripten_output.sh'
      - 'Source/Rust/**'
      - 'Tools/dora-rust/**'
      - 'Assets/Script/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Source/**'
      - 'Projects/Emscripten/**'
      - 'Tools/build-scripts/build_emscripten.sh'
      - 'Tools/build-scripts/build_wa_web.sh'
      - 'Tools/build-scripts/check_emscripten_output.sh'
      - 'Source/Rust/**'
      - 'Tools/dora-rust/**'
      - 'Assets/Script/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.74
          actions-cache-folder: emsdk-cache
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-emscripten
      - name: Build Web/WASM
        run: JOBS=2 Tools/build-scripts/build_emscripten.sh
      - name: Verify package
        run: Tools/build-scripts/check_emscripten_output.sh
      - name: Upload Web package
        uses: actions/upload-artifact@v4
        with:
          name: dora-ssr-web
          path: result/dora-ssr-web
