name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip CI]') && !contains(github.event.head_commit.message, '[skip Linux]')"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libgl1-mesa-dev libssl-dev
    - name: Generate Lua bindings
      run: |
        sudo apt-get install lua5.1
        sudo apt-get install -y luarocks
        sudo luarocks install luafilesystem
        cd ./Tools/tolua++
        lua tolua++.lua
    - uses: dtolnay/rust-toolchain@stable
    - name: Make
      run: |
        cd Projects/Linux
        make x86_64
